### ISSUE TITLE
SubMap - Forbidden Land - Teleporter

### ISSUE THREAD

**Issue by dragoonsouls** [Legend-of-Dragoon-Modding/Severed-Chains#1005]
There is a little Visual Error in the Teleporters from Kadessa - AKA Forbidden Land. Some of them looks erroneous.
![teleporter_kadessa](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/17453375/380d35d5-e8b4-41c1-b43f-cb6468b652ec)

**Comment by LordMonoxide** [comment]
Closed in 35e7cd1
