### ISSUE TITLE
Shop Menu Softlocks

### ISSUE THREAD

**Issue by dragoonsouls** [Legend-of-Dragoon-Modding/Severed-Chains#1008]
Pretty much as the title says, some of the Shop Menu, specially **Item** Shop, will Softlock if you don't buy a thing. Tested and replicated several times only to check if was happening randomly, here a list of shops that happened:
Item Shop at Bale
Item Shop at Black Castle
Item Shop at Velweb
Weapon Shop at Deningrad (before DD attack) - Not Always? ** 

** This one happened just a single time (maybe)... but it happens.

The condition to trigger this is entering a shop, enter to the buy list, came out and quit the shop menu

**Comment by Chocolate06** [comment]
Shopkeeper gets stuck in an animation loop

https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/132630165/e4c1e30d-4b7d-4645-9521-63432d1d3bd0

**Comment by LordMonoxide** [comment]
Found the issue - if open the shop before the shopkeeper's animation finishes, it gets stuck in a loop after you close the shop
