### ISSUE TITLE
Passing Disk 3 to 4 bug

### ISSUE THREAD

**Issue by dragoonsouls** [Legend-of-Dragoon-Modding/Severed-Chains#1009]
The first time i got from Disk 3 to 4, got a collision displacement under **main.opengl** not sure if related with the collision code, here's a brief description of what happened:
_Passing from Disk 3 to 4 directly make Dart walking at the edge of the SubMap without casting the Entrance CutScene, where characters are walking by the desert_

**Comment by LordMonoxide** [comment]
Note: only happens if you start on disk 3 and play through to disk 4. If you save the game before the disk change and reload it, it works

**Comment by hunterwescreation** [comment]
https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/150770573/d62da675-9e21-40b5-bd3f-8ae39fe95a24

**Comment by avionanx** [comment]
Happens because dart is not on intended collision primitive 48. From dart's script: 

This section of code on triggers once, on the initial load, before the controller loop. Walking to collision primitive will not trigger the cutscene.
```
call SMap::scriptCheckSelfCollision, stor[24] ; collisionPrimitiveIndex
jmp_cmp ==, 0x3a, stor[24], inl[:LABEL_22] ; operand, left, right, addr
jmp_cmp ==, 0x1, stor[24], inl[:LABEL_23] ; operand, left, right, addr
...

LABEL_22:
jmp inl[:LABEL_35] ; addr``
...

LABEL_35:
call Scus94491BpeSegment::scriptSetIndicatorsDisabled, 0x1 ; disabled
call SMap::scriptSetTitleCardAnimationPauseTicks, 0xc8 ; ticks
call SMap::scriptLoadChapterTitleCard, 0x4 ; titleNum
