### ISSUE TITLE
SubMap CutScenes Issues

### ISSUE THREAD

**Issue by dragoonsouls** [Legend-of-Dragoon-Modding/Severed-Chains#1010]
Some of the SubMaps CutScenes have major visual bugs, here is a list of what i found, with a little description:
Home of Giganto - SubMap Breaking Gate - Gigantic Haschel.
Velweb Diaz Throne - Zieg Explaining Creation - Most of the Visuals are corrupted.

**Comment by LordMonoxide** [comment]
Closing as these are now referenced in other issues
