### ISSUE TITLE
SubMaps Visual Issues

### ISSUE THREAD

**Issue by dragoonsouls** [Legend-of-Dragoon-Modding/Severed-Chains#1011]
Most of them related surely with the OpenGL implementation:
The two major bugs are this.
Top of Deningrad Library had a very strange looking texture (and corrupted) at the very right (seems to be something translucent miss).
Rouge-Aglis Translucent Mirror where Savan is looking.

**Comment by LordMonoxide** [comment]
Closed in 35e7cd1
