### ISSUE TITLE
Retail Bugged 3D Models

### ISSUE THREAD

**Issue by dragoonsouls** [Legend-of-Dragoon-Modding/Severed-Chains#1012]
Found some of the "Retail bugged models":
Claire (From SubMaps CutScenes in which Haschel recall her).
Old Man on Bale Library (Have his face Texture on the chest).
Lenus - Dragoon Minimodel (In my run i see that she lacks of face textures).

I will try to patch those in this days, but be patient.

**Comment by dragoonsouls** [comment]
Find out that the Lenus Dragoon MiniModel actually is not bugged on the 3D model, but in the Texture, have no palette for the Face.

**Comment by LordMonoxide** [comment]
This ticket has been split up into others
