### ISSUE TITLE
Displaced Collisions

### ISSUE THREAD

**Issue by dragoonsouls** [Legend-of-Dragoon-Modding/Severed-Chains#1013]
Found some displaced collisions during my run, the two more notorious are:
Fletz - After night Nello's house, when passing to the "next day".
Lidiera Town - After leaving the Pete house when he finds Dart and Rose at the Cavern.

Both of them share something similar, you get larger CutScenes in both and you get from inside a house to the exterior immediately after the finishing of the Scene.

**Comment by LordMonoxide** [comment]
Resolved
