### ISSUE TITLE
Merchant at first arrival to Hellena under bridge before bridge is lowered

### ISSUE THREAD

**Issue by hunterwescreation** [Legend-of-Dragoon-Modding/Severed-Chains#1040]
When arriving in Helena for the first time, when you have to hide behind the merchant cart, the merchant himself can be seen holding on under the drawn bridge. When the bridge is lowered, the merchant disappears, assumedly back to his position on the merchant cart.

![Merchant](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/150770573/624df489-6cde-4f3d-a0af-fb5e827a0c8c)

**Comment by LordMonoxide** [comment]
Resolved by movement fixes
