### ISSUE TITLE
Awkward double fade in at shack and Lavitz + Shana's Z positioning being off

### ISSUE THREAD

**Issue by hunterwescreation** [Legend-of-Dragoon-Modding/Severed-Chains#1043]
When arriving at the shack where Shana treats Lavitz's wounds after Hellena, there are two issues with 1 video showing the problem.

1. There is supposed to be just one fade-in that happens which shows Lavitz being tended to by Shana. However, 2 fade-ins end up happening. One short fade which shows Lavitz standing up from a laying position (which you would normally never see), then another fade-in which is more in-line with retail. 

2. Lavitz's and Shana's Z-positioning is slightly off. Shana's left arm should be in front of Lavitz's left leg, but ends up being behind it, making it look like Shana is to Lavitz's right instead of in front of him.

https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/150770573/48419791-c1d2-4a7b-a066-e8fe5dd7d202

**Comment by LordMonoxide** [comment]
The Z ordering is an unfortunate effect of us actually using a proper Z-buffer, and the devs positioning the characters strangely. I fixed the fading which is the main issue, so I'm gonna consider this fixed.
