### ISSUE TITLE
Dragoon spirits stop for a Shirley Temple

### ISSUE THREAD

**Issue by LRCthousandwesside** [Legend-of-Dragoon-Modding/Severed-Chains#1048]
Second scene at Shirley's Shrine when they pull out DS spirits everything seems to work ok until they walk away, and the ds spirits keep glowing where the characters were standing and fade too late.

**Comment by hunterwescreation** [comment]
https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/150770573/53fb1c64-d8c6-4aeb-be6c-29ee093f1b62

Here is footage for how it looks now

**Comment by LordMonoxide** [comment]
Tested, this is not related to fast/auto text
