### ISSUE TITLE
Wrong warp at Hoax

### ISSUE THREAD

**Issue by hunterwescreation** [Legend-of-Dragoon-Modding/Severed-Chains#1058]
When going to see the handmaiden, the window entrance warps you to the ladder instead of the normal entrance.

https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/150770573/42bb3485-9667-4993-b69d-5bfbb60e46cf

**Comment by LordMonoxide** [comment]
Fixed by afc2cced
