### ISSUE TITLE
Shana levitates during scene at Bale

### ISSUE THREAD

**Issue by hunterwescreation** [Legend-of-Dragoon-Modding/Severed-Chains#1059]
Before the screen pans down to show Shana, she is already visible as if her coordinates are wrong.

https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/150770573/8ff565c7-e384-423b-86cc-7e4124d05c5e

**Comment by LordMonoxide** [comment]
Fixed in 6c0f6078
