### ISSUE TITLE
Dart leaves Shana behind

### ISSUE THREAD

**Issue by hunterwescreation** [Legend-of-Dragoon-Modding/Severed-Chains#1060]
When Shana is supposed to run away at the poison forest to catch her breath, she runs first. However, Dart runs first, leaving Shana in the wind.

https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/150770573/48f780dc-cdf5-414d-99e1-1780f6d83a0b

**Comment by LordMonoxide** [comment]
From Huntario: this is only happening with quicktext enabled

???

**Comment by hunterwescreation** [comment]
Seems to be fixed on latest release!

**Comment by LordMonoxide** [comment]
Fixed in 8aebb0df6c9af97a736605e9c04be958d27fa702
