### ISSUE TITLE
Saving makes Dart invisible

### ISSUE THREAD

**Issue by hunterwescreation** [Legend-of-Dragoon-Modding/Severed-Chains#1061]
Sometimes after saving, Darts' character model disappears

https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/150770573/5581d451-5854-4521-a5d8-60ab92ceecb3

.

**Comment by LordMonoxide** [comment]
Turns out this was due to the temporary M hotkey to enter freecam
