### ISSUE TITLE
carry Shana scene has strange artifact above characters

### ISSUE THREAD

**Issue by hunterwescreation** [Legend-of-Dragoon-Modding/Severed-Chains#1063]
When Shana hurts her ankle and Dart carries her, the scene is supposed to be pitch black, but there is something above the characters' heads

https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/150770573/c691a2b1-fa06-43eb-ab58-dd0320f4fca9

**Comment by warblgarbl** [comment]
Precision issue? What we're seeing is the very bottom of submap 111. Camera is positioned just a little too high for the cutscene.
Changing `call SMap::scriptSetCameraOffset, 0x0, 0xfffffeca` to `0xfffffec6` works, but I'm not sure if there's a better solution.

DRGN21/339/1
```
LABEL_91:
call Scus94491BpeSegment::scriptSetIndicatorsDisabled, 0x1 ; disabled
call Scus94491BpeSegment::scriptStopSoundsAndSequences ; index
call Scus94491BpeSegment::scriptWaitForFilesToLoad ; index
call Scus94491BpeSegment::scriptLoadMusicPackage, 0x43, 0x0 ; musicIndex, dontStartSequence
call SMap::scriptAttachCameraToSobj, stor[0], 0x0 ; scriptIndex, attach
call SMap::scriptSetModeParamForNextCallToScriptSetCameraOffsetOrHideSubmapForegroundObject, 0x2, 0x0, 0x0 ; mode, foregroundObjectIndex, out
call SMap::scriptSetCameraOffset, 0x0, 0xfffffeca ; x, y
```

![image](https://github.com/user-attachments/assets/ae78b745-edcd-4486-8bff-ea4277fc5301)
