### ISSUE TITLE
Z coordinate shenanigans

### ISSUE THREAD

**Issue by hunterwescreation** [Legend-of-Dragoon-Modding/Severed-Chains#1064]
Some characters positions are slightly off, so I will share all that I have found in photos. two are innkeepers and one is Dart being in the foreground when he is supposed to be behind bars
![20240112084022_1](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/150770573/b99aa2b9-e41e-4ec0-a917-2e5fd919b61f)
![20240112084036_1](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/150770573/eaad6a79-2154-4b5e-8c75-70624cb8dae0)
![20240112085931_1](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/150770573/8394d181-54a6-45af-ad31-0db49d595327)

**Comment by theflyingzamboni** [comment]
I suspect this is a result of 3D models using perspective projection, as the model primitives are no longer z-averaging to fall behind the cutouts.
