### ISSUE TITLE
Dart misaligned with ropes under Kazas

### ISSUE THREAD

**Issue by LRCthousandwesside** [Legend-of-Dragoon-Modding/Severed-Chains#1069]
Clip of darts ropes and floor clipping

https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/156335827/baf807dc-c62c-44b7-9a7e-9a47725124e1

**Comment by theflyingzamboni** [comment]
@LRCthousandwesside What is the issue that you are referring to here? Is it that Dart is in front of the platform when he climbs down? Or is it something about the tunnel area? I can't really see what he's doing at the end.

**Comment by LRCthousandwesside** [comment]
Yes he's in front of platform, as well clips rope wrong as well
