### ISSUE TITLE
Kazas elevators and gondola on the fritz

### ISSUE THREAD

**Issue by LRCthousandwesside** [Legend-of-Dragoon-Modding/Severed-Chains#1071]
Gondola in Kazas is a hot mess, same with elevators

**Comment by hunterwescreation** [comment]
https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/150770573/148eeebf-c136-4ae1-a8b6-f014c1d4218e

**Comment by LordMonoxide** [comment]
This is no longer occurring
