### ISSUE TITLE
Shirley light pulse seems to only affect untextured polys

### ISSUE THREAD

**Issue by LordMonoxide** [Legend-of-Dragoon-Modding/Severed-Chains#1075]
![image](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/437657/47c0b99f-1f96-4fdf-b923-612df1ae509c)

**Comment by RedDragoon101** [comment]
![Screenshot (418)](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/70169883/eb0764d2-9507-4839-9bec-80480e73df64)
