### ISSUE TITLE
Rose and Shana walk into eachothers models

### ISSUE THREAD

**Issue by hunterwescreation** [Legend-of-Dragoon-Modding/Severed-Chains#1081]
Outside the battle arena when Dart is about to start fighting, Rose and Shana walk away from the party. In retail, Rose walks slightly in front of Shana as they both leave the screen. However, in SC, Rose and Shana walk into eachother.

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/150770573/f38ba41a-ba28-4b93-8eef-89f446b8eff3

**Comment by LordMonoxide** [comment]
This was fixed with #1008
