### ISSUE TITLE
Dart and Lloyd's positions seems slightly off at Battle Arena waiting room

### ISSUE THREAD

**Issue by hunterwescreation** [Legend-of-Dragoon-Modding/Severed-Chains#1082]
Inbetween fights at the Battle Arena, Dart goes to talk to Hashel before Lloyd arrives and walks past them through the same doorway. In SC, both Dart and Lloyd can be seen clipping both of their arms into the doorway while walking through. However, in retail, they seem to only clip their hands slightly into the doorway. 

Below I have a reference for both when SC and retail go through the doorways to help.

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/150770573/5bf3a7a1-78eb-44d2-b23c-2a212f593d3b

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/150770573/4bdc8eaf-8207-4935-b954-0a6c4abcc5aa

**Comment by LordMonoxide** [comment]
I'm going to close this since it's a retail issue, but tfz will add it to his omnibus effect issues ticket to fix at a later time
