### ISSUE TITLE
Lavitz gets stuck in Hellena

### ISSUE THREAD

**Issue by hunterwescreation** [Legend-of-Dragoon-Modding/Severed-Chains#1083]
Right before you are supposed to fight the beast trapped in Hellena, everyone is looking for an exit. Lavitz however, seems to have a hard time not getting stuck. I saw him get stuck, filmed, reset the game and tried again, and he still got himself stuck.

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/150770573/3bbab9e1-c4e1-4b3e-8f2e-a0929ca3206d

**Comment by LordMonoxide** [comment]
He goes into his thinking animation several times and then starts walking into the wall

**Comment by warblgarbl** [comment]
This is the magical journey they send you on:

Setting up destination data:
```
JMP_fc4_5:
call SMap::scriptSelfLoadSobjAnimation, 0x1 ; walking animation
mov 0xfffffea9, stor[24] ; target x
mov 0x14, stor[25] ; target y
mov 0xffffff11, stor[26] ; target z
mov 0xfffffffc, stor[27] ; used as a flag to switch animations in Label 22-24 and for modifying movement ticks in Label 26
mov 0xa, stor[28] ; rotation frames
memcpy 0x3, stor[24], stor[8] ; copy destination coordinates
gosub inl[:LABEL_22] ; addr
mov 0x2d, stor[25] ; source, dest
gosub inl[:LABEL_67] ; addr
```

Label 22-24 is just a couple checks to change animations based on stor[27] before continuing to Label 25 (doesn't meet those conditions)
```
LABEL_25:
call SMap::scriptReadModelPosition, stor[0], stor[29], stor[30], stor[31] ; scriptIndex, x, y, z
jmp_cmp !=, stor[29], stor[24], inl[:LABEL_26] ; operand, left, right, addr
jmp_cmp !=, stor[30], stor[25], inl[:LABEL_26] ; operand, left, right, addr
jmp_cmp !=, stor[31], stor[26], inl[:LABEL_26] ; operand, left, right, addr
jmp inl[:LABEL_31] ; addr
```

After confirming Lavitz is at the same location, it sets s[24] to 1 (why?), then the Z value, before continuing to Label 67 loop hell when the value is negative.
```
LABEL_30:
mov stor[31], stor[24] ; source, dest
return
LABEL_31:
mov 0x1, stor[24] ; source, dest
jmp inl[:LABEL_30] ; addr
```

```
LABEL_67:
jmp_cmp ==, 0x0, stor[24], inl[:LABEL_69] ; operand, left, right, addr
yield
call SMap::scriptGetSobjCollidedWith2, stor[0], stor[26] ; sobjIndex, collided
jmp_cmp ==, 0x0, stor[26], inl[:LABEL_66] ; operand, left, right, addr
call Scus94491BpeSegment::scriptReadGlobalFlag1, stor[25], stor[26] ; flag, value
jmp_cmp !=, 0x0, stor[26], inl[:LABEL_68] ; operand, left, right, addr
while stor[24], inl[:LABEL_67] ; counter, addr
mov 0x0, stor[24] ; source, dest
jmp inl[:LABEL_69] ; addr
LABEL_68:
mov 0x1, stor[24] ; source, dest
LABEL_69:
return
```

**Comment by warblgarbl** [comment]
Jump table used for selecting animation sequences is randomized based on tick count, so it makes sense that it would occasionally try the same one twice in a row.
Basically identical script structure for Meru and Albert in Ch. 4 Aglis, but for some reason Albert never even attempts the same location. I set a breakpoint for the second coordinate check, and it never gets there. Not sure how it avoids it in one script and not the other when the sequences are randomized.

**Comment by LordMonoxide** [comment]
If he selects the same movement entry in his action jump table twice in a row, he'll try to move to the same coordinates. In 2.1, we see those coordinates being off by one, but in the devbuild they match exactly, and this seems to break it.

2.1:
```
DEBUG: script[12].storage[29] -423
DEBUG: script[12].storage[24] -424
DEBUG: script[12].storage[30] 20
DEBUG: script[12].storage[25] 20
DEBUG: script[12].storage[31] -104
DEBUG: script[12].storage[26] -103
```
