### ISSUE TITLE
Haschel stuck in animation loop at home of giganto

### ISSUE THREAD

**Issue by LRCthousandwesside** [Legend-of-Dragoon-Modding/Severed-Chains#1091]
After rejoining Haschel and choosing team members before Gerich fight he gets stuck in animation loop

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/156335827/195a9b17-9210-4cc1-92a8-2e433135f39b

**Comment by hunterwescreation** [comment]
I just had this exact experience. I was using the change party feature to take Dart out of my party. After 2 failed attempts at getting into the fight, I decided to put Dart back into my party to see if it would work and it did. 

Not sure if that was the solution or not, but that is what I experienced.

**Comment by LRCthousandwesside** [comment]
Dart was in my party I haven't tried that feature yet

**Comment by LordMonoxide** [comment]
This was fixed with #1008
