### ISSUE TITLE
Second story (going up left stairs) in painters house in Bale bugged.

### ISSUE THREAD

**Issue by rand0command0** [Legend-of-Dragoon-Modding/Severed-Chains#1092]
When going up left stairs, next screen loads with no characters. Cannot walk back to first floor. Have to quit to menu and reload save.

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/74906451/4f4435db-9979-4983-a1d0-fe9902ddd8c8

**Comment by LordMonoxide** [comment]
If this is on the dev build, it's a known issue and already fixed in the opengl branch

**Comment by rand0command0** [comment]
You know what I believe I may have actually downloaded the wrong branch...somehow haha

 Just wanted to add if this is your brain child your work is absolutely fantastic. I never gave this game a solid try as a kid, and after finding this im anxious to give it a legit playthrough. Appreciate all your help!

**Comment by LordMonoxide** [comment]
Greatly appreciated! We plan to have the next release out in the first quarter of this year, and public test builds out within a month. Feel free to close this issue if you're satisfied with the resolution

**Comment by rand0command0** [comment]
Looking forward to it!

**Comment by rand0command0** [comment]
Looking forward to it!
