### ISSUE TITLE
Guard flickers in and out of existence. 

### ISSUE THREAD

**Issue by hunterwescreation** [Legend-of-Dragoon-Modding/Severed-Chains#1093]
After our first meeting with the king, if you go back and forth at the entrance, a guard will flicker into existence.

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/150770573/ec2692f1-92b3-4ec8-9afd-3f6feb2e8d66

**Comment by LordMonoxide** [comment]
The guards on either side are actually the same guard. When you see him in the middle, it's the interpolation code trying to smooth his warp from one side to the other.
