### ISSUE TITLE
Wingly attacking Wink has weird pulsating effect.

### ISSUE THREAD

**Issue by hunterwescreation** [Legend-of-Dragoon-Modding/Severed-Chains#1095]
When the wingly who attacks Wink starts powering uo, there is the stange pulsating effect not found in retail.

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/150770573/4d1723e6-4d7f-4fa7-951e-23433e5c506a

**Comment by LordMonoxide** [comment]
Likely related to #1075

**Comment by warblgarbl** [comment]
Fixed by 966ff567
