### ISSUE TITLE
Teleporter before fighting Lloyd is broken

### ISSUE THREAD

**Issue by hunterwescreation** [Legend-of-Dragoon-Modding/Severed-Chains#1096]
When doing the teleporter puzzle to get to Lloyd, one of the teleporters causing your character to be unable to move or perform any action that isn't pausing the game. 

Submap 444

Must use debugger to get to 446.

445 is Faust so may want to avoid.

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/150770573/0565cf32-8251-40fc-a042-2a6a5b042667

**Comment by LordMonoxide** [comment]
I suspect this is caused by the new collision code, whoever works on this should check the collision debugger first

**Comment by LordMonoxide** [comment]
Looks like this was broken before we branched for opengl

**Comment by LordMonoxide** [comment]
This was broken in 54aea4df781a88e7427b9a20a8aed2de5231942f
