### ISSUE TITLE
Character models glow during scene with Doel

### ISSUE THREAD

**Issue by hunterwescreation** [Legend-of-Dragoon-Modding/Severed-Chains#1097]
When you first neet Doel and before he reveals himself to be Darts father, there is a scene that explains the different species. During this scene, the models glow weirdly as in the video below.

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/150770573/8a1173c5-07b3-4daa-bd96-540fd260fe08

**Comment by LordMonoxide** [comment]
Apparently LOD tries to use negative colours in some cutscenes, needs to be treated as signed
