### ISSUE TITLE
Entering Home of Giganto from the world map causes the camera to quickly pan to where it should be pointing

### ISSUE THREAD

**Issue by LordMonoxide** [Legend-of-Dragoon-Modding/Severed-Chains#1100]
May need to look at the script, it seems to set the camera position a bunch of times, but I verified in retail that it is supposed to start in the top left, rather than panning up on a diagonal.

**Comment by avionanx** [comment]
Disabling all camera calls (scriptAttachCameraToSobj, scriptSetCameraOffset) in Dart's script still triggers the issue. File 2 cannot be decompiled and other files do not call any camera code.

**Comment by avionanx** [comment]
Script expects screen offset to be immediately updated after calling scriptSetCameraOffset
