### ISSUE TITLE
Arrows point the wrong direction when entering Home of Giganto for the first time

### ISSUE THREAD

**Issue by LordMonoxide** [Legend-of-Dragoon-Modding/Severed-Chains#1101]
It looks like they're being frisbeed at you

**Comment by Wulves** [comment]
I actually captured this as footage but didn't post because I thought it was retail lol

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/170744536/4dbef4bf-c3b3-439e-9ba2-a9535f95810f
