### ISSUE TITLE
Mayfil bridge alignment 

### ISSUE THREAD

**Issue by LRCthousandwesside** [Legend-of-Dragoon-Modding/Severed-Chains#1106]
Bridge is not aligned properly 
![17061990584332606626356464501484](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/156335827/481d7a86-e544-4b32-b0c2-9faaa243c1fe)

**Comment by LordMonoxide** [comment]
Closing in favour of #1254
