### ISSUE TITLE
Shana's Detonate Arrow not working.

### ISSUE THREAD

**Issue by linlinxza** [Legend-of-Dragoon-Modding/Severed-Chains#1111]
As shown in the video:

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/4374cb57-9d2d-44a0-b0ac-eef395ebeb72

As of commit: https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/commit/481e723772d8a077c2364c2ee7c0cb5ed56c5f95

**Comment by LordMonoxide** [comment]
Fixed by cb6e67f84b16cd254ad6741c8e287e84c3ab7b29
