### ISSUE TITLE
Can't swap out characters that originally need to be present for certain major boss battles.

### ISSUE THREAD

**Issue by linlinxza** [Legend-of-Dragoon-Modding/Severed-Chains#1112]
Can't swap out characters that originally need to be present for certain major boss battles. The game window will just crash with audio running in the background. Happened after battle with Gehrich.

As of commit: https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/commit/481e723772d8a077c2364c2ee7c0cb5ed56c5f95

**Comment by LordMonoxide** [comment]
Closing in favour of tracking document https://docs.google.com/spreadsheets/d/14gH3SDnXKe929-nQTsmmjhvjOiIQbsgYT_hYKEkfbfg/edit#gid=0
