### ISSUE TITLE
Major rendering issues with OpenGL during scene after battle with Gehrich and Mappi.

### ISSUE THREAD

**Issue by linlinxza** [Legend-of-Dragoon-Modding/Severed-Chains#1113]
Major rendering issues with OpenGL during scene after battle with Gehrich and Mappi. Was able to get through the scene. Suspect this to be a recurring issue with other after major boss battles with scenes in the game.

As of commit: https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/commit/481e723772d8a077c2364c2ee7c0cb5ed56c5f95

**Comment by LordMonoxide** [comment]
This has improved quite a bit now. Remaining issues:
- A few weird camera angles
- Gehrich is inside of the steps
- Kongol "smoke" after throwing statue is weird

**Comment by linlinxza** [comment]
The Kongol "smoke" happened even on the PS1.

**Comment by LordMonoxide** [comment]
Gherich is no longer inside of the stairs, other two issues still present
