### ISSUE TITLE
Unable to do random battles in Undersea Cavern area. Just shows black screen with BGM.

### ISSUE THREAD

**Issue by linlinxza** [Legend-of-Dragoon-Modding/Severed-Chains#1114]
Unable to do random battles in Undersea Cavern area. Just shows black screen with BGM. If I change the battle field from the one in the Undersea Cavern, the battle will load properly.

As of commit: https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/commit/481e723772d8a077c2364c2ee7c0cb5ed56c5f95

**Comment by LordMonoxide** [comment]
Closing for now, will re-open if reproduced
