### ISSUE TITLE
Dramatic song starts too early when Lenus is revealed

### ISSUE THREAD

**Issue by linlinxza** [Legend-of-Dragoon-Modding/Severed-Chains#1117]
Song should start when Emile says, "Wait!!"

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/2beae712-ff3c-4255-9263-e056ff3d68e7

As of commit https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/commit/481e723772d8a077c2364c2ee7c0cb5ed56c5f95

**Comment by LordMonoxide** [comment]
Fixed in fa5c0790
