### ISSUE TITLE
Render scale has major issues.

### ISSUE THREAD

**Issue by Seperest** [Legend-of-Dragoon-Modding/Severed-Chains#1118]
I don't know what sort of monster machines you guys have but the effects of 1-5 are as follows for me.
1: Extremely blocky with minor stuttering.
2: A tad less blocky, with minor stuttering. Battle scene has heavy stuttering.
3: Looks like normal PS1, Field has minor stuttering, Menu has major stuttering, battle stutter is unplayable.
4: Good looking. Very choppy and slow. Unplayable. Battles start crashing when I have 3 party members.
5: Crash.

Specs:
Windows 10 pro.
AMD Ryzen 5 3600 6 Core
16GB DDR4 RAM
Nvidia GeForce GTX 1660 Ti 6GB

All drivers are up to date. Tried restarting comp with nothing else open, same results.

Not sure if I'm missing something lol.

**Comment by Seperest** [comment]
Any eta on next release? I realize its a volunteer project so no exact date can be given, just something along the lines of days, weeks, months, years, would be fine. :P

**Comment by LordMonoxide** [comment]
We expect to finish it in the first quarter of this year
