### ISSUE TITLE
MF crash 2.0

### ISSUE THREAD

**Issue by LRCthousandwesside** [Legend-of-Dragoon-Modding/Severed-Chains#1122]
Crashed during Melbu Frama stage 2, Dart Albert and Kongol in party, during stage 2 all as dragoon, Albert was sucked into stage 2 MF, when he was about to be ejected it crashed log attached
[debug.log](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/files/14092759/debug.log)

**Comment by LRCthousandwesside** [comment]
![mf 2 1](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/156335827/6de37f92-6158-4331-8c45-5cdc37180f53)
![MF 2 2](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/156335827/e546a696-8279-4f1c-8f12-36033361b4af)
[debug.log](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/files/14092858/debug.log)

**Comment by LRCthousandwesside** [comment]
https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/156335827/bca86dc6-aaea-40f9-a483-dd12d5280859

**Comment by LordMonoxide** [comment]
This was resolved by 14286ee
