### ISSUE TITLE
Dart walking on ladders instead of climbing in Deningrad Library

### ISSUE THREAD

**Issue by linlinxza** [Legend-of-Dragoon-Modding/Severed-Chains#1124]
https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/6fb63b63-9da1-46fb-aabd-380ccfb3d7bf

As of commit https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/commit/af4cf92c302859d22ea5280b7a65ca26144be7c9

**Comment by avionanx** [comment]
retail behavior
