### ISSUE TITLE
Iffy looking text dialog boxes

### ISSUE THREAD

**Issue by linlinxza** [Legend-of-Dragoon-Modding/Severed-Chains#1128]
![Iffy looking text dialog](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/c44603b9-d4e8-495f-ac48-b8d2fb499adc)

As of commit https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/commit/e3c2532bb989aefb63917c73abdac9ff85351ae4

Continues on with newer commits.

**Comment by LordMonoxide** [comment]
This is likely resolved as of the latest commit

**Comment by linlinxza** [comment]
> This is likely resolved as of the latest commit

Confirmed.
