### ISSUE TITLE
Jiango deff crash with character count below 3

### ISSUE THREAD

**Issue by avionanx** [Legend-of-Dragoon-Modding/Severed-Chains#1134]
Battle object slots are hardcoded, script will crash if 1 or 2 characters are absent on rock drop attack

**Comment by LordMonoxide** [comment]
Closing in favour of tracking document https://docs.google.com/spreadsheets/d/14gH3SDnXKe929-nQTsmmjhvjOiIQbsgYT_hYKEkfbfg/edit#gid=0
