### ISSUE TITLE
Michael plants Dart and Rose into the ground.

### ISSUE THREAD

**Issue by linlinxza** [Legend-of-Dragoon-Modding/Severed-Chains#1136]
https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/be32c2f2-f089-4bf4-985e-02a4d6c2fd8a

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/a359b68a-a6cd-43a4-9405-1f7a6944d777

As of commit https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/commit/b895f25ae7a1cafac86fbcf12de7bb5438f8a69f

**Comment by LordMonoxide** [comment]
Resolved by 7d9a782
