### ISSUE TITLE
Melbu of 2nd generation; laser attack crashes game (Game Breaker)

### ISSUE THREAD

**Issue by linlinxza** [Legend-of-Dragoon-Modding/Severed-Chains#1137]
https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/9e1f2772-c137-4e7e-b5fc-7e74f27e5f3d

`02:41:20.133 [Hardware legend.game.scripting.ScriptManager:184] ERROR: Script 51 crashed!
02:41:20.133 [Hardware legend.game.scripting.ScriptManager:185] ERROR: File 5436/1[addr 0x3e1c]
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:186] ERROR: Parameters:
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:187] ERROR:   Op param: 0x2e2
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:189] ERROR:   1: script[51].storage[19] -1
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:189] ERROR:   2: script[0xf90] 0x0
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:189] ERROR:   3: script[51].storage[8] -20000
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:192] ERROR: Storage:
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:194] ERROR:   1: 0x33
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:194] ERROR:   2: 0xffffffff
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:194] ERROR:   3: 0xffffffff
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:194] ERROR:   4: 0xffffffff
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:194] ERROR:   5: 0xffffffff
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:194] ERROR:   6: 0xffffffff
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:194] ERROR:   7: 0xffffffff
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:194] ERROR:   8: 0x90000
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:194] ERROR:   9: 0xffffb1e0
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:194] ERROR:   10: 0x2
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:194] ERROR:   11: 0x1
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:194] ERROR:   12: 0xffffffff
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:194] ERROR:   13: 0xffffffff
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:194] ERROR:   14: 0xffffffff
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:194] ERROR:   15: 0xffffffff
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:194] ERROR:   16: 0xffffffff
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:194] ERROR:   17: 0xffffffff
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:194] ERROR:   18: 0xffffffff
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:194] ERROR:   19: 0xb7
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:194] ERROR:   20: 0xffffffff
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:194] ERROR:   21: 0xffffffff
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:194] ERROR:   22: 0xffffffff
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:194] ERROR:   23: 0xffffffff
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:194] ERROR:   24: 0x2
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:194] ERROR:   25: 0xffffffff
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:194] ERROR:   26: 0xffffffff
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:194] ERROR:   27: 0xffffffff
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:194] ERROR:   28: 0xffffffff
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:194] ERROR:   29: 0xffffffff
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:194] ERROR:   30: 0xffffffff
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:194] ERROR:   31: 0xffffffff
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:194] ERROR:   32: 0xffffffff
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:194] ERROR:   33: 0xffffffff
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:197] ERROR: Call stack:
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:203] ERROR:   1: 0
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:203] ERROR:   2: 0
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:203] ERROR:   3: 0
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:203] ERROR:   4: 0
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:203] ERROR:   5: 0
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:203] ERROR:   6: 0
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:203] ERROR:   7: 0
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:203] ERROR:   8: 0
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:203] ERROR:   9: 0
02:41:20.134 [Hardware legend.game.scripting.ScriptManager:203] ERROR:   10: 0
02:41:20.134 [Hardware legend.core.RenderEngine:897] ERROR: Shutting down due to exception:
java.lang.RuntimeException: An error occurred while ticking script 51`

As of commit https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/commit/b895f25ae7a1cafac86fbcf12de7bb5438f8a69f

**Comment by avionanx** [comment]
From melbu's deff script:
I can patch the script to work rather than changing engine code if I know how this is originally supposed to behave
```
...
mov 0xffffb1e0, stor[stor[stor[0], 15], 8] ; source, dest
mov 0x2, stor[stor[stor[0], 15], 9] ; source, dest
mov 0x1, stor[stor[stor[0], 15], 10] ; source, dest
call SEffe::scriptAddLifespanAttachment, stor[15], stor[23] ; effectIndex, ticks
call SEffe::scriptLoadSameScriptAndJump, stor[15], inl[:LABEL_66] ; scriptIndex, address
...
; FORK RE-ENTRY
LABEL_66:
mov stor[9], stor[23] ; source, dest
LABEL_67:
call Battle::scriptRand, stor[18], 0x0, 0x1000 ; value, min, max
call Battle::scriptRand, stor[19], 0x0, stor[8] ; value, min, max
