### ISSUE TITLE
Lenus crashes when party member count below 3

### ISSUE THREAD

**Issue by avionanx** [Legend-of-Dragoon-Modding/Severed-Chains#1139]
Lenus will crash when her turn begins(?)
One of Lenus' DEFF scripts will crash when she uses AOE disc attack

**Comment by LordMonoxide** [comment]
Closing in favour of tracking document https://docs.google.com/spreadsheets/d/14gH3SDnXKe929-nQTsmmjhvjOiIQbsgYT_hYKEkfbfg/edit#gid=0
