### ISSUE TITLE
Weird glitch in Lohan stadium after being defeated by Lloyd (Potential game breaker)

### ISSUE THREAD

**Issue by linlinxza** [Legend-of-Dragoon-Modding/Severed-Chains#1142]
https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/6390ae36-810c-46a3-972b-d3c4ee24d200

Something like this might relate to the issue:

`02:29:06.311 [Hardware legend.core.opengl.TmdObjLoader:379] WARN : SobjModel (index 13) part 14 has translucent untextured face but no translucency override!`

As of commit https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/commit/376bb88d87400e15e77c49993cffae21568fce3c

**Comment by avionanx** [comment]
non-zero movement step on submap load, caused by floats and
```
call SMap::scriptReadModelPosition, stor[0], stor[8], stor[9], stor[10] ; scriptIndex, x, y, z
call SMap::scriptSelfMoveToPosition, stor[8], stor[9], stor[10], 0x1 ; x, y, z, movementTicks
