### ISSUE TITLE
Blocky spores in Nest of dragon

### ISSUE THREAD

**Issue by LRCthousandwesside** [Legend-of-Dragoon-Modding/Severed-Chains#1147]
Spore textures in nest of dragon are strange, blocky
![17080213558891558411530911623593](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/156335827/c5e5f12f-6efa-4738-8197-603688557f93)

**Comment by LRCthousandwesside** [comment]
River is weird too

**Comment by LordMonoxide** [comment]
Closed in 35e7cd1
