### ISSUE TITLE
Game Over screen doesn't render

### ISSUE THREAD

**Issue by Illeprih** [Legend-of-Dragoon-Modding/Severed-Chains#1148]
Screen is black, otherwise it works as intended

**Comment by DrewUniverse** [comment]
Side note: retail behavior requires pressing Start on the Game Over screen to return to the title screen. Many players may not remember that, thinking it doesn't work when they try to press X. I'm hesitant about changing retail behavior, but I think we should do something extra. Whether it's allowing any key to advance to title screen, or an auto-advance after X seconds. Thoughts?

**Comment by LordMonoxide** [comment]
@DrewUniverse Both SC and retail allow pressing X
