### ISSUE TITLE
Meru Dragoon rendering issues

### ISSUE THREAD

**Issue by linlinxza** [Legend-of-Dragoon-Modding/Severed-Chains#1161]
https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/d1fa0ce9-fe7b-44a3-a181-889b63223c2a

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/52a06af6-6966-4ed4-b65d-8363ee194b54

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/37216613-b3ff-421b-ac58-5327e391ddb4

**PS1 comparison:** https://youtu.be/ZIsKi5Hoqws

**As of commit:** https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/commit/36afc40ca26eb5fcc640b388710f077c3984306e

**Comment by LordMonoxide** [comment]
Closing now that many things are implemented, we will be opening new tickets for individual issues
