### ISSUE TITLE
Attack Items cause spinning effect (Also some rendering issues)

### ISSUE THREAD

**Issue by linlinxza** [Legend-of-Dragoon-Modding/Severed-Chains#1163]
**Attack Items with spinning effect that affect enemy status:**

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/f89d3261-0c68-49e7-9373-5f9244510825

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/4c605158-d883-42e7-9136-731da38aa79c

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/24490134-d53e-41b3-b0c3-7f9778c59546

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/fc2a1d24-a7c5-4a3a-b776-33a7098c0bb0

**Some with rendering issues (also spinning effect):**

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/a945e3ab-4808-4720-b7ab-c760159f24ab

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/87415355-49e5-4809-877b-4370ebb388d3

Flash Hall and Thunderbolt should have more lightning effects.

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/7da5dd11-6bc5-4169-b904-9fd1fc2cca8b

Trans Light isn't as flashy.

**Multi attack items spinning issue:**

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/2423b575-ed38-4bca-87ac-22f1acbbf517

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/6ea474ee-3627-49b3-9e01-7d78543a53ed

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/e2191121-5e84-4986-b35b-cea246889e7a

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/813fa3c4-662b-4101-87af-498c8d43ac2b

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/9f40d73c-d015-4cde-bdc3-fc8bc56f963f

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/218b2096-dfe5-418d-a2d6-fd7bed12a272

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/e20569d9-1428-4407-9c27-dc62f530d2db

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/c2b6b49e-8acc-4009-95f3-7646a677ba05

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/607c86a6-99f0-4d39-963d-7a4cc9e5b659

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/51daa868-6e3f-494e-822b-8dc62af8eaee

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/3f72126d-d035-4003-bdec-07ad0f5138fe

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/caebff46-1b75-4cfb-af4c-f48fda4ceaef

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/b9f1a4f7-44c2-424c-8eb8-00c8dd28cd35

This is issue with the spinning is only the case with multi attack items it seems.

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/f49695f2-efe1-43f5-81b7-38807261ea3e

Also, for any of those multi attack items, the X button with the number and percent sign is missing.

**As of commit:** https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/commit/36afc40ca26eb5fcc640b388710f077c3984306e

**Comment by LordMonoxide** [comment]
Closing now that many things are implemented, we will be opening new tickets for individual issues
