### ISSUE TITLE
Shana Dragoon rendering issues

### ISSUE THREAD

**Issue by linlinxza** [Legend-of-Dragoon-Modding/Severed-Chains#1165]
https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/b6658a4f-a94b-471b-9b13-0dac352bebaa

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/ec672953-1d66-4174-a379-e17401d8af75

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/c1753ea2-d9ad-4b7c-b45b-96728202c158

**PS1 comparison:** https://youtu.be/RVXRCTfdBfA

**NOTE: Miranda as a Dragoon will have the same rendering issues.**

**As of commit:** https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/commit/36afc40ca26eb5fcc640b388710f077c3984306e

**Comment by LordMonoxide** [comment]
Closing now that many things are implemented, we will be opening new tickets for individual issues
