### ISSUE TITLE
Rose Dragoon rendering issues

### ISSUE THREAD

**Issue by linlinxza** [Legend-of-Dragoon-Modding/Severed-Chains#1166]
https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/d02618a3-2f16-4484-ba67-228cbb032d31

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/d3cb9c25-b571-4759-9f17-238eb2af940d

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/df3d0b10-f602-4a40-963d-063a90035b18

**PS1 comparison:** https://youtu.be/Y59f-3Y2InE

**As of commit:** https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/commit/36afc40ca26eb5fcc640b388710f077c3984306e

**Comment by LordMonoxide** [comment]
Closing now that many things are implemented, we will be opening new tickets for individual issues
