### ISSUE TITLE
Kongol Dragoon rendering issues

### ISSUE THREAD

**Issue by linlinxza** [Legend-of-Dragoon-Modding/Severed-Chains#1167]
https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/6167c323-f8b8-4a5e-bf25-d6a954cc02b9

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/86682c8e-eb47-4bd4-8851-da722a04e23a

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/f1fe3fb0-97e4-4f88-af77-cd9ab7e8b2e2

**PS1 comparison:** https://youtu.be/_Hknm2e56Es

**As of commit:** https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/commit/36afc40ca26eb5fcc640b388710f077c3984306e

**Comment by LordMonoxide** [comment]
Closing now that many things are implemented, we will be opening new tickets for individual issues
