### ISSUE TITLE
Haschel Dragoon rendering issues (Also, he has no eyes!)

### ISSUE THREAD

**Issue by linlinxza** [Legend-of-Dragoon-Modding/Severed-Chains#1168]
https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/07aa64f7-ddef-467a-8b36-d6e8703f848e

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/ca261845-7af1-48ad-b9ff-0f78c653ea78

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/2d933203-1f2f-4cc5-b07f-223c1d6f48a1

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/5f2634fa-936b-4d32-8a82-516b3e326644

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/30c7e007-4870-4401-b7b8-27936f951af9

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/d038ae41-f7b9-4eb9-ac17-65b7770fe120

**PS1 comparison:** https://youtu.be/rvhPskriq1k

**As of commit:** https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/commit/36afc40ca26eb5fcc640b388710f077c3984306e

**Comment by LordMonoxide** [comment]
Closing now that many things are implemented, we will be opening new tickets for individual issues
