### ISSUE TITLE
Dart Dragoon rendering issues (Red Eye)

### ISSUE THREAD

**Issue by linlinxza** [Legend-of-Dragoon-Modding/Severed-Chains#1169]
https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/82fd410a-df42-4d5e-bc27-6c8c282c99dc

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/6b08f1c0-053b-4a54-8007-54f914ef80f2

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/8a8c95ec-95bf-42e8-9981-16f5c6437720

**PS1 comparison:** https://youtu.be/tRykLv4ZqEU

**As of commit:** https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/commit/36afc40ca26eb5fcc640b388710f077c3984306e

**Comment by LordMonoxide** [comment]
Closing now that many things are implemented, we will be opening new tickets for individual issues
