### ISSUE TITLE
Dart Dragoon rendering issue (Divine)

### ISSUE THREAD

**Issue by linlinxza** [Legend-of-Dragoon-Modding/Severed-Chains#1170]
https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/0627764f-2001-4b5b-9a0b-80cdeaf73dd0

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/395f057e-49c0-4b92-b3b4-037d1ac5098a

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/3e019261-bb47-4f67-a259-e32bcd944315

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/a4257e72-0296-4100-87d9-810439ce19f5

**PS1 comparison:** https://youtu.be/PR2W9qrf1EU

**As of commit:** https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/commit/36afc40ca26eb5fcc640b388710f077c3984306e

**Comment by LordMonoxide** [comment]
Closing now that many things are implemented, we will be opening new tickets for individual issues
