### ISSUE TITLE
Dragoon attack level gauge missing

### ISSUE THREAD

**Issue by linlinxza** [Legend-of-Dragoon-Modding/Severed-Chains#1179]
![Dragoon attack example](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/bb201ab4-6fe2-4b4a-84cd-396c65094e13)

This gauge determines when you have to tap the 'X' button. This is missing as shown in the example. The 'X' button is present. Just not the gauge above it.

As of commit https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/commit/ed46b5f89b6481e0dd7f409e23a6833d6d5135ad

**Comment by LordMonoxide** [comment]
Blending isn't quite right, but I'm opening a separate ticket for that
