### ISSUE TITLE
Crash during battle

### ISSUE THREAD

**Issue by RedeemedRiku** [Legend-of-Dragoon-Modding/Severed-Chains#1192]
Was on the world map between valley of corrupted gravity and home of giganto. got into a battle with a blue bird, the blue bird fled and as soon as it did, the game crashed. the game window closed out but the console remained open. running RB3 lod-game-67fca1acd7d649c6497808bcc593523fbe2317f1.jar
![image](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/163367986/9ccc933b-734a-43a9-8651-86f2fc7128d9)

**Comment by LordMonoxide** [comment]
This was due to pressing triangle to open the inventory select menu. This code has been changed already and it is no longer an issue.
