### ISSUE TITLE
"Failed to unpack files: Failed to located disk images"

### ISSUE THREAD

**Issue by nai249** [Legend-of-Dragoon-Modding/Severed-Chains#1194]
Can't get the game to start, looked through the other issues and it looks like no one else is having this issue.

**Comment by LordMonoxide** [comment]
You need to provide disk images so SC can extract the game assets. Take a look at the setup guide [here](https://legendofdragoon.org/guides/setup-severed-chains/). If you're still having trouble, pop into our [#player-help](https://discord.com/channels/307164262063669248/408013767151058946) channel on discord.

**Comment by nai249** [comment]
Thanks, I didn't know you had to buy the physical game as well.
