### ISSUE TITLE
Kadessa warp bug

### ISSUE THREAD

**Issue by talmagal** [Legend-of-Dragoon-Modding/Severed-Chains#1195]
When entering into kadessa it warps you somewhere its not supposed to. 

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/36626394/7cc1d120-844a-4687-9457-0f8ad29d71eb

**Comment by LordMonoxide** [comment]
scriptMapTransition and renderEnvironmentAndHandleTransitions -> mapTransition are getting run in the wrong order
