### ISSUE TITLE
Lavitz's hug on Lavitz's mother is incorrect

### ISSUE THREAD

**Issue by Ink230** [Legend-of-Dragoon-Modding/Severed-Chains#1196]
**Branch:** Main
**Branch:** RB2

**Description**
When saying goodbye to Lavitz's mother, Lavitz hugs the air, and also walks backwards at an incorrect angle.

**Pics**
![image](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/29797557/9c2a3e06-94cb-4a73-b97e-72cabfda00db)

**Comment by FedoraMan12** [comment]
![image](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/167259569/4c33c976-6541-476f-8a8a-f984979753d6)
Her upper torso is above the walls

**Comment by warblgarbl** [comment]
His hug animation assumes you went out to gather supplies before telling her you're ready to leave Bale. When you leave and come back, she is standing closer to the table, in the correct position for his hug.

The z-order issue at the end of the scene applies to Lavitz as well.

Both the position and the z-order issues are retail.
