### ISSUE TITLE
Sandora Elite boss on death, chain is visible

### ISSUE THREAD

**Issue by Ink230** [Legend-of-Dragoon-Modding/Severed-Chains#1197]
**Branch:** Main
**Branch:** RB2

**Description**
When the Sandora Elite boss dies, the chain they use in one of their attacks, is also visible in the death animation.

**Pics**
![image](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/29797557/c8ee68b8-0950-4df5-ab26-b4e2f59f594b)

**Comment by Zychronix** [comment]
Retail behaviour.
