### ISSUE TITLE
Kongol's hitback animation seems to be missing frames?

### ISSUE THREAD

**Issue by Ink230** [Legend-of-Dragoon-Modding/Severed-Chains#1198]
**Branch:** Main
**Branch:** RB2

**Description**
When Kongol gets hit, it seems as if some animations are missing. He will switch between image 1 and image 2 within one frame.

This looks bad. Not sure if some animations are being missed or this is just the way it is.

**Pics**
![image](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/29797557/b6e0735a-ba35-4c81-87eb-bbd4f3bb4974)
![image](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/29797557/79fddc88-c5e1-4099-9e11-5d0a4d163f7e)

**Comment by Zychronix** [comment]
Retail behaviour! They really did not like Kongol for some reason :'(
![image](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/14896608/5ec89132-dc83-4aab-a308-783fb483b4dd)
![image](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/14896608/4b5aa9f2-9f17-4bcc-b7f5-f2481d05a292)
