### ISSUE TITLE
Baby Kongol

### ISSUE THREAD

**Issue by talmagal** [Legend-of-Dragoon-Modding/Severed-Chains#1208]
During the fight on the moon that never sets between kongol and indora. If you dont complete your addition and indora counters you, he also turns you into a baby. Also seems to affect the back and forth dialog. 

![20240409173553_1](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/36626394/d7ad2341-3f94-4607-b808-465c8c0f375c)

[https://cdn.discordapp.com/attachments/1171862923870752829/1227375767764336651/The_Legend_of_Dragoon_2024-04-09_17-50-03.mp4?ex=66282dc2&is=6615b8c2&hm=6879ed8b364f33cb625feef091ab45ba524be54e701539315fddd17b1ecfa6d1&](url)

**Comment by LordMonoxide** [comment]
This was broken in f6d6c3ef4d16f8cc7989a843a4dc6c2c735c78da
