### ISSUE TITLE
Certain effects cause models to go into LOD equivalent of T-pose

### ISSUE THREAD

**Issue by LordMonoxide** [Legend-of-Dragoon-Modding/Severed-Chains#1225]
- Melbu counter-attack
- One of Michael's attacks

**Comment by dragoonsouls** [comment]
maybe it's related to some of the animations like CMB or LMB?, at least if specific to DEFFs... if a T-Pose appears, means that the array containing those animations don't exist... because are not processed properly or maybe because are not processed at all

**Comment by theflyingzamboni** [comment]
closed by #1518
