### ISSUE TITLE
New Campaign with no save data crashes on Continue

### ISSUE THREAD

**Issue by abauerly** [Legend-of-Dragoon-Modding/Severed-Chains#1228]
If a New Campaign is started and the game is not saved, the "Save Game" folder exists and so "Continue" is an option from the main menu. If the corrupted save is selected, the game crashes.

[ididnotsaveanddied.txt](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/files/15055077/ididnotsaveanddied.txt)

**Comment by LordMonoxide** [comment]
Also should be noted - newer builds will not actually create the campaign until a save is made, so you won't end up with empty and unusable campaigns
