### ISSUE TITLE
"Goods" object / item description incorrect

### ISSUE THREAD

**Issue by abauerly** [Legend-of-Dragoon-Modding/Severed-Chains#1229]
Issue is present in both RB2 and devbuild. At the beginning of the game, when the only 2 Goods are "War Bulletin" and "Father's Stone." Regardless of which item is highlighted, the description shown is only for "Father's Stone."

![Screenshot 2024-04-21 172549](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/59266445/8a9beeb6-a36c-41e5-ba75-1fd4419ab2cd)

I noted a similar bug with item description updating reported in #1200 .

**Comment by RedDragoon101** [comment]
Issue is not specific to the start of the game, It has to do with the Left and Right Column not updating the description when scrolling to and from each other. Pressing up or down updates it.
