### ISSUE TITLE
Boy's Textbox is Blank when Lavitz's Mom is called Grandma

### ISSUE THREAD

**Issue by RedDragoon101** [Legend-of-Dragoon-Modding/Severed-Chains#1257]
Severed Chains - 
![Screenshot (347)](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/70169883/e4e87970-05ba-4507-a038-b73619388f95)
Retail - 
![Screenshot (353)](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/70169883/b89ed5c6-7f70-41ac-8e5c-3636a7c9b851)

**Comment by avionanx** [comment]
char · is missing from the font
