### ISSUE TITLE
Law Launcher Background effects messed up

### ISSUE THREAD

**Issue by RedDragoon101** [Legend-of-Dragoon-Modding/Severed-Chains#1258]
![Screenshot (354)](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/70169883/d7f3b441-9965-482f-b811-c93f5d2305bb)
![Screenshot (356)](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/70169883/96297b64-82b5-4d31-893c-decf6a8ab1cc)

**Comment by LordMonoxide** [comment]
Closed in 35e7cd1
