### ISSUE TITLE
Shadows have some kind of extra jank at the back

### ISSUE THREAD

**Issue by LordMonoxide** [Legend-of-Dragoon-Modding/Severed-Chains#1260]
Note: this is with translucency disabled to see it more easily
![image](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/437657/1bb1b307-feee-4e5b-9369-394a18e136ca)

**Comment by dragoonsouls** [comment]
surely i'm wrong... but looks like a texture bleeding in there

**Comment by LordMonoxide** [comment]
![image](https://github.com/user-attachments/assets/c05837f3-039d-425d-8897-baea18b69ffa)
There is a CLUT getting loaded overtop of the shadow texture

**Comment by LordMonoxide** [comment]
This happens specifically if you load from the title screen to the world map and get into battle. The title screen loads CLUTs overtop of the shadow texture, and it's only smap that reloads the shadow texture into vram.
