### ISSUE TITLE
Music for the entire game disappears after defeating Kongol in Hoax

### ISSUE THREAD

**Issue by FedoraMan12** [Legend-of-Dragoon-Modding/Severed-Chains#1263]
This audio bug happens after the boss fight. Music is completely gone; however, you can still hear certain actions if you listen carefully.
https://youtu.be/Ic-rwEn3gkw

**Comment by LordMonoxide** [comment]
![image](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/437657/0e6cd002-3429-4f11-b5ab-fc647c207b5e)
Sequencer main volume gets set way too low
