### ISSUE TITLE
Script patcher borks itself, if a single patch fails

### ISSUE THREAD

**Issue by Illeprih** [Legend-of-Dragoon-Modding/Severed-Chains#1272]
Unpacker bug is still alive and well, making it possible for one of the DRGN files to not get unpacked properly.
Script patcher will try to patch it and fail, however all the previous patches are done, but not marked as done, making the second not work, since it's trying to patch already patched files.

**Comment by LordMonoxide** [comment]
@avionanx can you confirm this is resolved by your PR and close if so?

**Comment by avionanx** [comment]
Closed via #1289
