### ISSUE TITLE
Item effects go crazy or are missing

### ISSUE THREAD

**Issue by FedoraMan12** [Legend-of-Dragoon-Modding/Severed-Chains#1288]
Meteor fall (flashbang warning)
https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/167259569/e3ce6725-144f-4045-b4d8-4481f2edb907

Spear frost (Flashbang warning) flashing should be above the mist.
https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/167259569/36f1ded0-7170-497b-a2e5-8bbcf7021f89

Spark net is missing the lines (they add on as it gets stronger 
https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/167259569/2990e30c-cf36-462d-9958-4ad005d5e86c

Burn out, Flashes go SUPER hard in this one, camera zoom is ok.
https://youtu.be/XS3-lbu1104

Detonate rock (ignore the long pause when throwing the item) missing the trail and explosions (the cloud shape)

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/167259569/7087b196-e16a-4fed-a36e-f191c505e12f

**Comment by LordMonoxide** [comment]
Turns out this is a retail thing, the larger the enemy the larger the flashes
