### ISSUE TITLE
Add an option to disable the BGM music during game play and battles? (Since audio is being worked on presently).

### ISSUE THREAD

**Issue by linlinxza** [Legend-of-Dragoon-Modding/Severed-Chains#1299]
Add an option to disable the BGM music during game play and battles? (Since audio is being worked on presently). Be great if we could use our own music when playing the game.

**Comment by DrewUniverse** [comment]
SC will feature volume sliders for different aspects of the game (bgm, sfx, etc.). It is a part of the wishlist page [here](https://github.com/orgs/Legend-of-Dragoon-Modding/projects/3).

**Comment by linlinxza** [comment]
Okay then.
