### ISSUE TITLE
Shana transformation feathers block out other rendering but don't actually render

### ISSUE THREAD

**Issue by LordMonoxide** [Legend-of-Dragoon-Modding/Severed-Chains#1308]
I'm thinking we might have to do translucency sorting on ortho and perspective in the same queue

See #1307 for renderer

![image](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/437657/7d53602a-3e73-4614-bdc2-f276488aac27)

**Comment by LordMonoxide** [comment]
![image](https://github.com/user-attachments/assets/af540ad7-802a-4bd4-b028-9e83b1423924)
It appears this is actually retail behaviour

**Comment by theflyingzamboni** [comment]
This is how the effect is supposed to look.
