### ISSUE TITLE
Status Magic Item Effects not working

### ISSUE THREAD

**Issue by RedDragoon101** [Legend-of-Dragoon-Modding/Severed-Chains#1313]
![Screenshot (410)](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/70169883/370d92b7-95e3-4f46-8842-40f4d73825ec)
![Screenshot (412)](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/70169883/76a09e82-d9f2-4c52-be8d-afc4a1cd68cb)

**Comment by RedDragoon101** [comment]
![Screenshot (415)](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/70169883/91562e69-e6e1-4487-bc18-c60e2cfedc10)

**Comment by FedoraMan12** [comment]
https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/167259569/0b5d591e-5048-4a19-b0b6-6f5094dea688


https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/167259569/eeab7423-8381-42a4-845b-21b3e31f9112


https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/167259569/19dd588e-06c2-4d27-b78d-aa00c00c1581


https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/167259569/a32460d3-c3f9-472b-8185-594aea90c312
