### ISSUE TITLE
WMAP shadow translucency wrong

### ISSUE THREAD

**Issue by theflyingzamboni** [Legend-of-Dragoon-Modding/Severed-Chains#1328]
Seems to just be transparent instead of rendering in B-F.

![image](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/55669985/f202ca71-2e58-4cd6-bbaf-b8dd824e2324)

**Comment by LordMonoxide** [comment]
Broken by 176a822aed777ccb4c2dfd948c51b6eabd85dcea
Only happens after going from submap back to world map
