### ISSUE TITLE
Boat in marshlands rotation is bugged

### ISSUE THREAD

**Issue by LordMonoxide** [Legend-of-Dragoon-Modding/Severed-Chains#1334]

**Comment by avionanx** [comment]
occurs in other boat sequences aswell

**Comment by avionanx** [comment]
Dart instantly rotates isntead of rotating with boat in retail

**Comment by avionanx** [comment]
multiple scriptSetModelRotate calls per single frame on different axis, causing previous interpolation to be overridden
