### ISSUE TITLE
Moon Serenade Effects doesnt render correctly

### ISSUE THREAD

**Issue by RedDragoon101** [Legend-of-Dragoon-Modding/Severed-Chains#1338]
https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/70169883/6928ebd2-f3c2-4a31-840c-b9621180334f

**Comment by LordMonoxide** [comment]
Strange, the first effect didn't render over Meru at all...?

**Comment by LordMonoxide** [comment]
This has been resolved
