### ISSUE TITLE
Dancing Light Item Issues

### ISSUE THREAD

**Issue by RedDragoon101** [Legend-of-Dragoon-Modding/Severed-Chains#1346]
Starting transition and Ending transition are not retail, the Yellow Sparks that appear on the top of the screen are flashing too large.

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/70169883/00d835a6-f9d6-49f1-8249-98df4b6aef51

**Comment by LordMonoxide** [comment]
Transitions fixed in 62d48a6e

**Comment by LordMonoxide** [comment]
It turns out that the size of those sparks is based on the enemy size, closing
