### ISSUE TITLE
soft-locked

### ISSUE THREAD

**Issue by akapunk** [Legend-of-Dragoon-Modding/Severed-Chains#1363]
I saved my game right in front of a treasure chest in kazas.. im in sort of a 2d 'underground' section before entering the castle...

i happened to save the game on top of a treasure chest and its just completely soft locked my only save file cuz my character is basically stuck inside the chest and cant move as soon as i load the file ... is there anyway to fix this or download/import a generic save file so i can continue playing the game from close to the same point im at?? it was my only save file and im like 10 hours into the game fml

**Comment by LordMonoxide** [comment]
Press F12 to open the debugger
Select submap debugger from the dropdown in the top left corner
Adjust the first submap object's position slightly and press "set"

You should also make a new save each time, SC has unlimited saves :)
