### ISSUE TITLE
Audio Thread crash using Astral Drain on Drake

### ISSUE THREAD

**Issue by Chocolate06** [Legend-of-Dragoon-Modding/Severed-Chains#1364]
Consistent while playing at 3x speed

[Astral Drain.txt](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/files/15456507/Astral.Drain.txt)

**Comment by Chocolate06** [comment]
Also have gotten this on Shana's Star Children and Damia's Blea Sea Dragon so far

**Comment by avionanx** [comment]
also happens on flameshot
