### ISSUE TITLE
Shrine of Shirley Bugs (Apperently there's a lot)

### ISSUE THREAD

**Issue by DubboYeah** [Legend-of-Dragoon-Modding/Severed-Chains#1370]
On the dev stream tonight I noticed a few bugs in Shirley's Shrine and so i'm going to just drop the things i noticed here (note: most of these seem to be visual effect bugs)

obvious i think 
![image_2024-05-25_180358787](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/170837146/c81df378-c10c-40e9-99c1-09f6ee4e1af1)
expected: no black

obvious i think part 2
![image_2024-05-25_180311992](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/170837146/acfcb025-c078-4e9c-9d51-87d577771b4c)
expected: no black

text box should be white
![nah](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/170837146/1eae0897-9559-49aa-9ca7-eaf8a8106d93)

~every time shirley switches to a different model (works fine until the disc thing goes halfway down then it transforms to this)~
![image_2024-05-25_181317716](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/170837146/d2b75cae-23f9-4ae6-a8a5-ef9ee5af484e)
~expected: the disc stays the same size and does not become infinitely wide~

~~ladder is slanted a little bit~~
![unali](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/170837146/6279a5d2-8755-4ffd-934e-3180ae872b5c)

~~expected ladder:~~
![image_2024-05-25_183217788](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/170837146/5dc3b8fa-7c34-4bfc-94a2-91f60154ff1b)
Ladder fixed by 6b6244bd

**Comment by DrewUniverse** [comment]
To clarify, for this image where Dubbo said textbox should be white: what's actually wrong is that the textbox background is showing the submap content underneath. The textbox should remain blue, not white. Here is SC vs Retail.


![image](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/70291675/5dd385dc-38f2-4e11-b396-b68cc83fcca8)
![image](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/70291675/5dd385dc-38f2-4e11-b396-b68cc83fcca8)
![image](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/70291675/5dd385dc-38f2-4e11-b396-b68cc83fcca8)
![image](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/70291675/ecda8440-f754-4a3d-87f0-7012182f9ba4)
![image](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/70291675/ecda8440-f754-4a3d-87f0-7012182f9ba4)
![image](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/70291675/ecda8440-f754-4a3d-87f0-7012182f9ba4)

**Comment by DrewUniverse** [comment]
This also takes place with other white-flash effects, such as during the Hero Competition. 

![image](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/70291675/1ebdad60-57f9-4c6e-910a-df75e14830c9)
![image](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/70291675/59b416a8-a043-4194-82e8-a19b0b603965)
