### ISSUE TITLE
Text for specifiying 'generations' behind characters in Melbu battle (text should overlap everything)

### ISSUE THREAD

**Issue by linlinxza** [Legend-of-Dragoon-Modding/Severed-Chains#1372]
![Screenshot_20240528_185040](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/11242593/72f145ad-557d-4c56-867f-f49ea77b2d22)

As of commit: https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/commit/62d48a6e5967828ef7db53d3cf64659872ab64e2

**Comment by Zychronix** [comment]
Same issue as #1403
