### ISSUE TITLE
Green Bar at Phantom Ship

### ISSUE THREAD

**Issue by Wulves** [Legend-of-Dragoon-Modding/Severed-Chains#1374]
**Describe the bug**
There's a bright green bar at the bottom of the screen. On the brightside, the ghost flames are visible now in this section.

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains-Public-Test/assets/170744536/3737cf29-7752-49be-b20d-2975d4c4658f

**Comment by theflyingzamboni** [comment]
This is an issue with the retail background itself.
