### ISSUE TITLE
Phantom Chest Puzzle Textbox Not Appearing

### ISSUE THREAD

**Issue by Wulves** [Legend-of-Dragoon-Modding/Severed-Chains#1390]
After inputting a code, the chest should produce one of two text boxes as a means to better deduce the code to open it. This bug removes the hint. No idea what could be causing it, and it's inconsistent to boot, as other times it worked fine. This is at the stage where the item in chest is ultimate wargod, but I've also confirmed this happens after obtaining the ultimate wargod from the chest as well. I've used the exact same input (124) and the chest has both given and not given the hint.

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/170744536/b3a1ee91-7a61-4e1f-92e9-d379ad8461ef

**Comment by LordMonoxide** [comment]
Fixed by 4f7344d
