### ISSUE TITLE
World Map text box a bit too large - Text alignment - Text Color - Transparent on 3rd Zoom

### ISSUE THREAD

**Issue by Ehko4** [Legend-of-Dragoon-Modding/Severed-Chains#1399]
**Describe the bug**
The WM text boxes are larger than retail. The text color for areas outside the next story target are blue. Text alignment seems centered instead of left aligned. Upon zooming out the 3rd time, the next destination for story becomes transparent. 

**To Reproduce**
1. Go to the World Map
2. Zoom out to see next target if needed
3. Press 'Start' for location names to pop up.

**Expected behavior**
Colors to be the same. Text boxes the same size. 

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/170750797/aad3d3d9-e1b4-4ee5-b7f2-18911f901a9a

**Comment by LordMonoxide** [comment]
These have all been resolved
