### ISSUE TITLE
Addition Zoom Flare Effect Cuts Off (Likely Wide Screen Issue)

### ISSUE THREAD

**Issue by Wulves** [Legend-of-Dragoon-Modding/Severed-Chains#1411]
![Addition Flare Issue](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/170744536/c3e9cc96-21e7-492c-86ac-976f24c23297)

**Comment by LordMonoxide** [comment]
I'm fine with this one, it isn't a rectangular cutoff and doesn't look bad imo
