### ISSUE TITLE
Flickering Issues Happening on Non-1x Render Scales

### ISSUE THREAD

**Issue by nullgato** [Legend-of-Dragoon-Modding/Severed-Chains#1420]
### Description
Severed Chains (Recommended Build #⁠2) seems to have flickering issues on my machine running Linux - EndeavourOS (latest build). I have tried running at multiple render scales at different window dimensions, as well as trying to force disable VSync in the debugger menu. What I learned was that different render scales affect how fast the flickering occurs. There do seem to be "sweet spots" between the render scale and window resolution that produce a lesser amount of flickering.

Running with a render scale value of x1 seems to be of no issue.

### System Info
**OS:** EndeavourOS rolling x86_64 (latest build as of this date)
**Kernel:** Linux 6.9.3-arch1-1
**CPU:** i9-11900F
**RAM:** 32 GB
**GPU:** NVIDIA GeForce RTX 3080
**Display:** 2560x1440 @ 360Hz
**Window Manager:** KWin (Wayland)
**Display Environment:** KDE Plasma (6.0.5)

### To Reproduce
- Run Severed Chains by opening a terminal in the game's directory and running `./launch`
- Once the main menu is available, go into options and change the Render Scale to any value other than 1x

### Evidence
In this video transparency is enabled for the window, but even when I disable it's transparency it still occurs.

[Screencast_20240603_193435.webm](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/161165437/dce1d3cb-d6f4-494c-b908-9a189b65fcd9)

**Comment by LordMonoxide** [comment]
Do you have a discord account? If so can you pop into the #severed-chains channel on the LOD server so we can discuss this?
https://discord.gg/legendofdragoon

**Comment by LordMonoxide** [comment]
Resolved on discord, not an SC issue
