### ISSUE TITLE
Menu Discrepancy - Armed/Item Box

### ISSUE THREAD

**Issue by Wulves** [Legend-of-Dragoon-Modding/Severed-Chains#1428]
Honestly I feel like this is could be saved as an accessibility feature because it's a bit easier to read, but it is not retail so thought I'd make note.

![Menu Sell Wrong](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/170744536/051594b8-02ea-4a9a-b174-711f7c200e9f)

**Comment by Wulves** [comment]
This also occurs when buying a weapon as the prompts (Buy item?) and (Equip item?) are in their own box in the same way.

**Comment by LordMonoxide** [comment]
Intended change
