### ISSUE TITLE
Text Box Misplacement before Kamuy Fight

### ISSUE THREAD

**Issue by Wulves** [Legend-of-Dragoon-Modding/Severed-Chains#1456]
In retail it appears above Dart's head, but in SC it goes to the bottom corner where the other NPC dialogue appears later.

![Kamuy Retail](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/170744536/ca63178d-a2b5-4df3-933f-efffeabc3ccb)
![Kamuy SC](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/170744536/c3242425-6b4a-4e02-80e3-e7b3526cf8f8)

**Comment by avionanx** [comment]
LAB_8003da00 is broken
