### ISSUE TITLE
Lohan Cutscene - Shana's feet are blue

### ISSUE THREAD

**Issue by DrewUniverse** [Legend-of-Dragoon-Modding/Severed-Chains#1460]
On first visit. 

![image](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/70291675/ba90f004-4acc-4ced-b98d-5cfc07187481)

**Comment by LordMonoxide** [comment]
Currently operating on the assumption that texture remapping is broken for high res textures
`SECT/DRGN21.BIN/425/textures`
