### ISSUE TITLE
Known Retail Issue - Use Item Menu Line

### ISSUE THREAD

**Issue by Wulves** [Legend-of-Dragoon-Modding/Severed-Chains#1463]
Dead center a line of pixels is offset which cuts right through Haschel's portrait and otherwise just stands out as odd.

![Middle Row](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/170744536/89326571-4045-470d-ba34-e840022b41de)

**Comment by LordMonoxide** [comment]
Not fixing, menus will be overhauled at a later date
