### ISSUE TITLE
Scripts that require patches for registry support

### ISSUE THREAD

**Issue by avionanx** [Legend-of-Dragoon-Modding/Severed-Chains#1478]
DRGN21/453, DRGN22/453 (Lohan)
`call Scus94491BpeSegment_8002::scriptTakeItem, 0xd3, stor[25]`

DRGN1/332 (Unused monster script)
`call Battle::scriptGetBentStat, stor[30], EQUIPMENT_ACCESSORY_SLOT, stor[10]`
`jmp_cmp !=, 0x7f, stor[10], inl[:LABEL_42]`

DRGN1/402 (Player Combat Script)
`call Battle::scriptGetBentStat, stor[0], EQUIPMENT_WEAPON_SLOT, stor[8]`
`call Battle::scriptGetBentStat, stor[0], EQUIPMENT_WEAPON_SLOT, stor[8]`
`call Battle::scriptGetBentStat, stor[0], EQUIPMENT_ACCESSORY_SLOT, stor[8]`
`call Battle::scriptGetBentStat, stor[0], EQUIPMENT_ACCESSORY_SLOT, stor[8]`

**Comment by avionanx** [comment]
DRGN1/40?
DRGN1/84?

**Comment by LordMonoxide** [comment]
Closed by #1624
