### ISSUE TITLE
Frozen Jet Animation

### ISSUE THREAD

**Issue by Wulves** [Legend-of-Dragoon-Modding/Severed-Chains#1479]
When the ice breaks the shards spin rapidly instead of drifting apart as seen in retail.

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/170744536/7e96e656-3bf2-414e-98f0-775acd45c0c5

**Comment by Zychronix** [comment]
https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/14896608/119957dd-0077-4615-98bc-dd69d6dbc0f3
