### ISSUE TITLE
Grand Jewel Dark

### ISSUE THREAD

**Issue by Wulves** [Legend-of-Dragoon-Modding/Severed-Chains#1480]
The gems on the grand jewel are normally a bright yellow that goes into a dark orange, but in SC the colors seem to be a lot darker.

![Dark Jewel](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/170744536/6c9b25a9-cc2b-4407-a187-b66e06e55787)
![Grand Jewel Light](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/170744536/04252390-570a-4c52-826f-d9497abecca9)

**Comment by LordMonoxide** [comment]
This was fixed at some point
