### ISSUE TITLE
Text in Furni Displaying Incorrectly

### ISSUE THREAD

**Issue by Wulves** [Legend-of-Dragoon-Modding/Severed-Chains#1484]
Didn't bother finding out if this was retail since I figure we would want to fix it anyway. Occurs after DD attacks Deningrad.

![Text Jank](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/170744536/f6a85f36-3c73-412a-a8d2-22c5997798d6)

**Comment by avionanx** [comment]
retail behavior
