### ISSUE TITLE
My girl, Rosie, needs some work done on her Dragoon transformation and magic attack rendering.

### ISSUE THREAD

**Issue by linlinxza** [Legend-of-Dragoon-Modding/Severed-Chains#1506]
Certain effects are not rendering. Like when she poses after transformation. There is no black lightning effect when she transforms. Also, the 'rainbow effect' doesn't render behind her post transformation when she poses.

Also, there is no black box when she casts her 'Death Dimension' magic. And her 'Dark Dragon' attack is missing that white line when the dragon goes to attack.

**Comment by theflyingzamboni** [comment]
Splitting into #1561, #1562, #1563, #1564, #1566, #1567
