### ISSUE TITLE
problems launching game on MACOSM1

### ISSUE THREAD

**Issue by orioh369** [Legend-of-Dragoon-Modding/Severed-Chains#1515]
getting this error code on the log and on the launch game screen:
[Thread-1 legend.core.GameEngine:191] ERROR: Failed to unpack files
legend.game.unpacker.UnpackerException: java.lang.RuntimeException: Skipped the wrong number of bytes. End of file? Negative amount? (requested: 12, actual: -1677193820)

**Comment by LordMonoxide** [comment]
What are the sizes in bytes of each of your ISOs?

**Comment by orioh369** [comment]
1=484,951,824 bytes (487.5 MB on disk)
2=576,009,504 bytes (578.8 MB on disk)
3=559,173,888 bytes (562 MB on disk)
4=748,204,128 bytes (763.4 MB on disk)

**Comment by orioh369** [comment]
> What are the sizes in bytes of each of your ISOs?

[i got it running with fresh ISO files.]
