### ISSUE TITLE
Latest devbuild not working with infinite-mp-sp-1.0-SNAPSHOT.jar

### ISSUE THREAD

**Issue by linlinxza** [Legend-of-Dragoon-Modding/Severed-Chains#1517]
Latest devbuild not working with infinite-mp-sp-1.0-SNAPSHOT.jar

As of commit: https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/commit/3ba86699af43ad024760eee7d57b336051bb6ba1

**Comment by Zychronix** [comment]
Not related to SC itself, mods are separate.
