### ISSUE TITLE
Cut scenes do not work after battle where Dart needs to be present (crashes game window)

### ISSUE THREAD

**Issue by linlinxza** [Legend-of-Dragoon-Modding/Severed-Chains#1557]
Related to this commit: https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/issues/1550

Game window crashes when cut scene happens (where Darts deals the final blow to a boss) and another character besides Dart is in his place.

Example, Dragoon Doel. The cut scene works as expected. But when Dart is supposed to be in the picture, the window crashes, leaving nothing but the cut scene audio playing. Need to kill the Java process as a result.

I'd label this as a game breaker.

**Comment by avionanx** [comment]
Unlock party fixes have not yet been merged, things like cutscenes will still crash.

**Comment by linlinxza** [comment]
> Unlock party fixes have not yet been merged, things like cutscenes will still crash.

Okay. Just figured I'd bring it up.

**Comment by avionanx** [comment]
Closed by #1558 and #1572
