### ISSUE TITLE
Potential Status Chance Inaccuracies

### ISSUE THREAD

**Issue by Wulves** [Legend-of-Dragoon-Modding/Severed-Chains#1586]
Was talking to Lasagnaaammm and they mentioned a bug where sometimes 100% status chance doesn't proc. I removed evasion using the debugger when testing, but unless I made an error I had an instance where Urobolus' poison attack failed to proc. It was originally listed as 50%, but if it was 50% then I would have had to gotten a 1/256 (0.0039%) during the most recent test because it proc'd 9/9 times. That original 50% was taken from the JP Guidebook, which of course could just be wrong for our version, but if the probability is truly supposed to be 100%, then unless I made an error there's a bug lowering it to less than 100%. If we could get the data from the game for the probabilities, I could compare it to my findings to detect any status' that aren't behaving as intended.

**Comment by Zychronix** [comment]
I'm only able to replicate this WITH evasion in both SC and Retail. Did you turn off both evasion stats with the debugger? There is two accuracy checks done during a status effect attack, one for the damage and if the damage didn't miss another for actually applying the status effect. At least in the US International version there is no status chances on the monster side for Urobolus.
