### ISSUE TITLE
Speeding up the Game: Gravity Grabber Slow at Start

### ISSUE THREAD

**Issue by Wulves** [Legend-of-Dragoon-Modding/Severed-Chains#1596]
While the circle is being drawn the game slows down to 15 fps regardless of what speed it is set to, but returns to normal once the lights vanish. Likely related to the tentacle slow down in #1595. My best guess is that attacks using a glowing light aren't speeding up properly for some reason since that's the only link between the two attacks I can see.

**Comment by theflyingzamboni** [comment]
Cannot replicate, not happening for Wulves anymore either.
