### ISSUE TITLE
Dart Stuck Within NPC and Cannot Move

### ISSUE THREAD

**Issue by ironorr1984** [Legend-of-Dragoon-Modding/Severed-Chains#1597]
I must have done a "save anywhere" right at a starting point of an NPC, and now when I load the save point, Dart is stuck within the NPC, and I cannot move him out of it. I am now in a way, soft locked and cannot progress in the game. Is there a way I can mess with the .dsav file to move Dart to another location and get him out of the NPC?

Here is a screenshot. I forget the name of the NPC, but he is a merchant in this town. I can talk to him and initialize a sale, but other than that, I cannot get out of inside the NPC and continue the game.

![image](https://github.com/user-attachments/assets/570ff867-43bb-4139-96f1-01d8daa26db0)

**Comment by LordMonoxide** [comment]
1. Press F12 to open the main debugger
2. In the menu in the top left of the corner, select "submap debugger"
3. Dart will already be selected in the submap object list
4. Adjust his X or Z position slightly and press update
