### ISSUE TITLE
Divine Dragoon Dart doing wrong Damage

### ISSUE THREAD

**Issue by dragoonsouls** [Legend-of-Dragoon-Modding/Severed-Chains#1619]
While in the 2nd Generation of Melbu Frahma i got transformed using the special command (making the Divine Dragon Dimension [Battle Stage]), after that Melbu changed from "absorbing" to "shooting" Battle Stage and lost the Divine Dragoon Dimension, but also the free addition grants by it, after performing a 3 hit Addition, Dart did 12 Damage. After i made a 4 hit addition and did 200 more or less of Damage...

**Comment by LordMonoxide** [comment]
Duplicate of #1593
