### ISSUE TITLE
man in hood facing wrong direction

### ISSUE THREAD

**Issue by Lothar635** [Legend-of-Dragoon-Modding/Severed-Chains#1641]
man in the hood is facing the wrong direction in conversation with Fruegel

https://github.com/user-attachments/assets/ca83e656-9551-477c-89d9-77852d7d38fe

**Comment by Lothar635** [comment]
skip to 1 minute in the video

**Comment by LordMonoxide** [comment]
I'm guessing this was broken by 248b945c137e992211378550fc35305030f0690e
