### ISSUE TITLE
Automatic save conversion deletes memcard file

### ISSUE THREAD

**Issue by theflyingzamboni** [Legend-of-Dragoon-Modding/Severed-Chains#1643]
Users may want to keep the actual memcard file for further use and could have it accidentally deleted entirely if they just move the file in. Conversion should therefore maintain the original file. Could move it to another folder to keep the saves file cleaner, but this could result in people not realizing their memcard was preserved, so it may be best just to leave it there, or put it in a subfolder.

**Comment by LordMonoxide** [comment]
- Add a simple messagebox (see MessageBoxScreen) that asks if you want to delete the memcard
- If you choose no, the save conversion will pop again next time you load the title screen (i.e. restart the game or choose the "quit" option ingame)
- This will rely on #1644 being completed first or you'll be into an infinite loop of choosing not to convert and the game popping the menu back up
