### ISSUE TITLE
Meru Hair Transparency

### ISSUE THREAD

**Issue by Wulves** [Legend-of-Dragoon-Modding/Severed-Chains#1666]
**Describe the bug**
Meru's hair appears to be transparent, allowing you to see textures you shouldn't be able to. Super noticeable when she twirls, you can actually see the back of her face through her hair.

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/170744536/e0271ee4-b1bc-41dc-92a1-b0c1812c0645

**Comment by Meruheart** [comment]
![meru 3](https://github.com/user-attachments/assets/95f5b266-ad32-434f-868f-40885b2eebd7)
![meru 1](https://github.com/user-attachments/assets/d5187ba9-6244-4b41-8e98-ba2d88fb9f09)
![meru 2](https://github.com/user-attachments/assets/ef3fdf89-755f-4327-bdb2-5e3c32182ef0)
![meru face](https://github.com/user-attachments/assets/3476522a-635c-4ae4-9996-a92c98a71b2b)

**Comment by LordMonoxide** [comment]
Info for testing bird:
Map: 666
Sobj: 10
