### ISSUE TITLE
Down Burst Missing Texture

### ISSUE THREAD

**Issue by Wulves** [Legend-of-Dragoon-Modding/Severed-Chains#1689]
**Describe the bug**
The initial wind and petals appear to be missing for the Down Burst attack item.

https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/170744536/b737d095-c74f-483d-9eba-08f89d1ab2dd

**Comment by theflyingzamboni** [comment]
Initial dust cloud was fixed by #1814
