### ISSUE TITLE
Water Reflections going through Dart in Act 4

### ISSUE THREAD

**Issue by Kearu** [Legend-of-Dragoon-Modding/Severed-Chains#1697]
Cutscene at night with Rose in Ulara in Disc 4. Water background of the fountain reflects through Dart's character model.

**To Reproduce**

1. Go to Ulara after the initial desert.
2. Advance story.

**Expected behavior**
Water reflects behind the character model.

**Screenshots/Videos**
<img width="293" alt="image" src="https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/22601343/be424f6f-10a8-4166-80d9-ec216af133a7">

**Comment by LordMonoxide** [comment]
Merging with #1722
