### ISSUE TITLE
Psychobomb X visual bug

### ISSUE THREAD

**Issue by Meruheart** [Legend-of-Dragoon-Modding/Severed-Chains#1718]
https://github.com/user-attachments/assets/77d74ac5-8a39-4437-bdb7-0dd5c18aac57

**Comment by LordMonoxide** [comment]
Fixed by ee5e8a2eda17f3fa3444c6add0af781a895ee8e3

**Comment by LordMonoxide** [comment]
Scratch that, missing central rainbow blob after first part
