### ISSUE TITLE
Replace Menu Crashes the Game in Open Party

### ISSUE THREAD

**Issue by RedDragoon101** [Legend-of-Dragoon-Modding/Severed-Chains#1732]
Im currently in Hellena Prison with only Dart, I have Open Party On, and the game crashes when I try to open the Replace Menu

**Comment by avionanx** [comment]
```    if(this.primaryCharIndex < 2 && (CONFIG.getConfig(CoreMod.UNLOCK_PARTY_CONFIG.get()) || (gameState_800babc8.charData_32c[gameState_800babc8.charIds_88[this.primaryCharIndex + 1]].partyFlags_04 & 0x20) == 0)) {```
This change is bad, as charIds are initialized to -1 when game starts
