### ISSUE TITLE
Melbu crash absorbing single character party

### ISSUE THREAD

**Issue by Chocolate06** [Legend-of-Dragoon-Modding/Severed-Chains#1741]
14:49:34.105 [Hardware legend.game.scripting.ScriptState:1236] ERROR: ScriptState[23] Empty EffectManager child, allocated by script 18 (Empty EffectManager child, allocated by script 17 (DEFF ticker for script 11 (Enemy combatant index 0)) from scriptAllocateEmptyEffectManagerChild) from scriptAllocateEmptyEffectManagerChild crashed!
14:49:34.105 [Hardware legend.game.scripting.ScriptState:1237] ERROR: File .\files\SECT\DRGN0.BIN\5432 CALL @ 0x23bc
14:49:34.105 [Hardware legend.game.scripting.ScriptState:1238] ERROR: Parameters:
14:49:34.106 [Hardware legend.game.scripting.ScriptState:1239] ERROR:   Op param: 0x81
14:49:34.106 [Hardware legend.game.scripting.ScriptState:1241] ERROR:   0: script[23].stor[27] 0xffffffff
14:49:34.106 [Hardware legend.game.scripting.ScriptState:1241] ERROR:   1: script[23].stor[24] 0xffffffff
14:49:34.106 [Hardware legend.game.scripting.ScriptState:1241] ERROR:   2: script[23].stor[25] 0xffffffff
14:49:34.106 [Hardware legend.game.scripting.ScriptState:1241] ERROR:   3: script[23].stor[26] 0xffffffff
14:49:34.106 [Hardware legend.game.scripting.ScriptState:1244] ERROR: Storage:
14:49:34.106 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   0: 0x17
14:49:34.106 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   1: 0xffffffff
14:49:34.106 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   2: 0xffffffff
14:49:34.106 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   3: 0xffffffff
14:49:34.107 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   4: 0xffffffff
14:49:34.107 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   5: 0xffffffff
14:49:34.107 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   6: 0xffffffff
14:49:34.107 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   7: 0x90000
14:49:34.107 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   8: 0xffffffff
14:49:34.107 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   9: 0xffffffff
14:49:34.107 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   10: 0xffffffff
14:49:34.107 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   11: 0xffffffff
14:49:34.107 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   12: 0xffffffff
14:49:34.107 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   13: 0xffffffff
14:49:34.107 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   14: 0xffffffff
14:49:34.107 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   15: 0xffffffff
14:49:34.107 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   16: 0xffffffff
14:49:34.107 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   17: 0xffffffff
14:49:34.107 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   18: 0xffffffff
14:49:34.108 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   19: 0xffffffff
14:49:34.108 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   20: 0xffffffff
14:49:34.108 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   21: 0xffffffff
14:49:34.108 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   22: 0xffffffff
14:49:34.108 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   23: 0xffffffff
14:49:34.109 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   24: 0xffffffff
14:49:34.109 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   25: 0xffffffff
14:49:34.109 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   26: 0xffffffff
14:49:34.109 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   27: 0xffffffff
14:49:34.109 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   28: 0x6
14:49:34.109 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   29: 0x16
14:49:34.109 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   30: 0xb
14:49:34.109 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   31: 0xffffffff
14:49:34.109 [Hardware legend.game.scripting.ScriptState:1246] ERROR:   32: 0xffffffff
14:49:34.109 [Hardware legend.game.scripting.ScriptState:1249] ERROR: Registry IDs:
14:49:34.109 [Hardware legend.game.scripting.ScriptState:1256] ERROR: Call stack:
14:49:34.110 [Hardware legend.game.scripting.ScriptState:1258] ERROR:   0: .\files\SECT\DRGN0.BIN\5432 0x23b0
14:49:34.110 [Hardware legend.game.scripting.ScriptState:1261] ERROR: Disassembly:
14:49:34.121 [Hardware legend.game.scripting.ScriptState:1281] ERROR:
14:49:34.122 [Hardware legend.game.scripting.ScriptState:1281] ERROR:   ; FORK JMP
14:49:34.122 [Hardware legend.game.scripting.ScriptState:1281] ERROR:   LABEL_43:
14:49:34.123 [Hardware legend.game.scripting.ScriptState:1281] ERROR:   23a8: gosub inl[:LABEL_3] ; addr
14:49:34.123 [Hardware legend.game.scripting.ScriptState:1281] ERROR:   23b0: mov var[34][1], stor[27] ; source, dest
14:49:34.123 [Hardware legend.game.scripting.ScriptState:1284] ERROR:   23bc: call Battle::scriptGetBentPos, stor[27], stor[24], stor[25], stor[26] ; bentIndex, x, y, z
14:49:34.123 [Hardware legend.game.scripting.ScriptState:1285] ERROR:   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
14:49:34.123 [Hardware legend.game.scripting.ScriptState:1288] ERROR:   23d0: call Battle::scriptSetBentPos, stor[28], stor[24], stor[25], stor[26] ; bentIndex, x, y, z
14:49:34.124 [Hardware legend.game.scripting.ScriptState:1288] ERROR:   23e4: call SEffe::allocateDeffTmd, stor[18], 0x2d901 ; effectIndex, flags
14:49:34.124 [Hardware legend.game.scripting.ScriptState:1288] ERROR:   23f0: call SEffe::scriptSetRelativePosition, stor[18], stor[28], 0x0, 0xfffffd00, 0x0 ; bobjIndex1, bobjIndex2, x, y, z
14:49:34.124 [Hardware legend.game.scripting.ScriptState:1288] ERROR:   240c: call SEffe::scriptSetRelativeRotation, stor[18], stor[28], 0x0, 0x800, 0x0 ; bobjIndex1, bobjIndex2, x, y, z
14:49:34.124 [Hardware legend.game.scripting.ScriptState:1288] ERROR:   2424: call SEffe::scriptSetRelativeScale, stor[18], 0xffffffff, 0xfffff000, 0x1000, 0x1000 ; bobjIndex1, bobjIndex2, x, y, z
14:49:34.125 [Hardware legend.core.RenderEngine:1133] ERROR: Shutting down due to exception:
java.lang.RuntimeException: An error occurred while ticking script 23
        at legend.game.scripting.ScriptManager.executeScriptFrame(ScriptManager.java:203)
        at legend.game.scripting.ScriptManager.tick(ScriptManager.java:61)
        at legend.game.Scus94491BpeSegment.lambda$gameLoop$45(Scus94491BpeSegment.java:423)
        at legend.core.RenderEngine.lambda$init$17(RenderEngine.java:504)
        at legend.core.opengl.Window$Events.onDraw(Window.java:697)
        at legend.core.opengl.Window.tickFrame(Window.java:337)
        at legend.core.opengl.Action.run(Action.java:46)
        at legend.core.opengl.Action.tick(Action.java:32)
        at legend.core.opengl.Window.run(Window.java:314)
        at legend.core.RenderEngine.run(RenderEngine.java:1131)
        at legend.core.GameEngine.start(GameEngine.java:251)
        at legend.game.Main.main(Main.java:24)
        at legend.game.MainWindows.main(MainWindows.java:33)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 108
        at legend.game.combat.Battle.scriptGetBentPos(Battle.java:2757)
        at legend.game.scripting.ScriptState.scriptExecuteSubFunc(ScriptState.java:1029)
        at legend.game.scripting.ScriptState.runOp(ScriptState.java:623)
        at legend.game.scripting.ScriptState.executeFrame(ScriptState.java:410)
        at legend.game.scripting.ScriptManager.executeScriptFrame(ScriptManager.java:199)
        ... 12 more

**Comment by Meruheart** [comment]
This only happens if you transform in dragoon during phase 2, if you remain in human form, it´s beatable
