### ISSUE TITLE
Damia won´t do her Blue-sea Dragon summon spell with a party less than 3

### ISSUE THREAD

**Issue by Meruheart** [Legend-of-Dragoon-Modding/Severed-Chains#1757]
In "LoD Combat - Enemy Abilities & Behavior" document says that she should do her summon in her thing attack, but she was stuck doing dragoon addition and Freezing Ring (that´s outside her Patterned Retaliate)

![image](https://github.com/user-attachments/assets/0f26ce29-ed2f-4148-969f-e69aa8339409)

**Comment by avionanx** [comment]
False positive
