### ISSUE TITLE
Debugger (F12) causes soft lock crash

### ISSUE THREAD

**Issue by ameyer117** [Legend-of-Dragoon-Modding/Severed-Chains#1771]
Perhaps I'm missing something important, but on the latest devbuild, when I press F12, the game soft locks with a message in the console:

```
Oct 20, 2024 4:01:03 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @4fcb38dd
```

Testing environment:
Macbook Pro M3 Max (ARM64)
MacOS_M1 build

**Comment by avionanx** [comment]
JavaFX Debugger doesnt work with Mac M1, our plan is to rewrite debugger in nuklear that supports all platforms.

**Comment by ameyer117** [comment]
Perfect, that was my guess, just wanted to make sure I wasn't missing something. Thank you!
