### ISSUE TITLE
Giganto Home - Party member cloning before Gehrich boss fight

### ISSUE THREAD

**Issue by warblgarbl** [Legend-of-Dragoon-Modding/Severed-Chains#1772]
Enter fight room with Haschel in slot 0.
Slot 2 member is moved to inactive.
Slot 1 member is moved to slot 2.
A second instance of Haschel is created, occupying both slot 0 and slot 1.
Both Haschels remain in the party even after Kongol joins.

Other observations on multi-instanced characters (probably known/expected behavior):
Duplicated characters share addition, normal, and dragoon level EXP.
When both/all active, they each generate addition and dragoon level EXP, but will only get one share of normal EXP, wasting 1-2 active slots' worth of normal EXP.
Active addition is also shared, so if you change it mid-battle for one, it changes for the other(s).

**Comment by LordMonoxide** [comment]
Are you in the discord server? We'd like to find out a bit more info from you

**Comment by warblgarbl** [comment]
Party composition before Haschel leaves is producing a variety of results.
Sometimes he leaves as intended.
Sometimes he leaves a clone in his place, either his own or one of another party member.

**Comment by warblgarbl** [comment]
This is what seems to be retail behavior when Haschel leaves the party to face Gehrich alone:
If Haschel is in slot 1 or 2, the character in the other slot is checked.
If the other character is not Meru, Haschel is replaced with Meru.
If the other character is Meru, Haschel is replaced with Shana.

Slot 0 is never checked or modified for obvious retail reasons. The same behavior above applies when unlock party is enabled, allowing the possibility of having 2 Haschels, 2 Shanas, or 2 Merus.
