### ISSUE TITLE
Stuck in a Treasure Chest

### ISSUE THREAD

**Issue by Grymlahv** [Legend-of-Dragoon-Modding/Severed-Chains#1777]
So, I have the save anywhere activated, I opened the three chests before the second fight with Freugal to save King Albert.
I made a few attacks and then he called for Rodriguez to attack, but the game kept showing a zoomed in Guftas just standing there.
I figured I'd just hard reset, but when I loaded the save, Dart was standing in the treasure chest closest to the screen unable to move as he is trapped in the bounding box.

**Comment by LordMonoxide** [comment]
1. Open the debugger with F12
2. Click the dropdown menu in the top left of the debugger and open the submap debugger
3. Adjust the first submap object (Dart)'s X or Z position slightly

Do you have any more info about the softlock you experienced during the fight?

**Comment by Grymlahv** [comment]
I was not in dragoon form, my party was Dart, Lavitz, Rose, I had not used any items up to that point, I had only attacked Rodriguez, and that's about it.

**Comment by Grymlahv** [comment]
Also thanks a bunch! that worked!

**Comment by DrewUniverse** [comment]
Guftas softlock sounds eerily familiar... but I think I encountered that over a year ago in RB2. Will try to reproduce.

**Comment by LordMonoxide** [comment]
Originally reported about a year ago #853 

Thanks for the info @Grymlahv, I'll link this ticket to the original one and close this one
