### ISSUE TITLE
Leaving Furni for the first time puts you behind Seles

### ISSUE THREAD

**Issue by LordMonoxide** [Legend-of-Dragoon-Modding/Severed-Chains#1778]
I've done some testing here, the problem is happening at `LAB_800e7c18`.

* `gameState_800babc8.wmapFlags_15c.get(locationIndex)` returns false making it overwrite the location
* `locationIndex` is 0x34
* At first I thought it should be getting set when arriving on the Queen Fury, but this isn't the case in 2.1
* In 2.1, `locationIndex` is 0x33

Further investigation is needed

**Comment by LordMonoxide** [comment]
Update:
If you force `gameState_800babc8.wmapFlags_15c.get(0x34)` (the wrong index) to be set it completely breaks wmap. You can't enter back into Furni and if you get into a battle it'll warp you into the ocean near Hellena after the fight

**Comment by LordMonoxide** [comment]
It's not happening when I run from the disk 3 intro, I get location 0x33 as expected

**Comment by LordMonoxide** [comment]
[save_1.zip](https://github.com/user-attachments/files/17580328/save_1.zip)

Here's a save with it broken. `this.mapState_800c6798.submapSceneFrom_c6` is 0x13 instead of 0x19 as in 2.1

**Comment by LordMonoxide** [comment]
In `updateCollidedPrimitiveIndexAndCheckForWorldMapTransition`, Dart's `collidedPrimitiveIndex_16c` is 0x13

**Comment by LordMonoxide** [comment]
When you're on this map for the first time and leave, your submap scene is 0x13. When you come back, it's 0x19 from then on. Somehow this save has it set to 0x19 already.

**Comment by theflyingzamboni** [comment]
Bug was in 2.1
