### ISSUE TITLE
Particles fly off rather than staying in confined area (status procs, status auras, other magic)

### ISSUE THREAD

**Issue by DrewUniverse** [Legend-of-Dragoon-Modding/Severed-Chains#1784]
![GIF 11-3-2024 4-33-22 PM](https://github.com/user-attachments/assets/e3a1b311-4a83-4edc-bcd7-8b9a421f0ebc)

![conf](https://github.com/user-attachments/assets/6049468a-757e-486a-81c2-aa985e023f34)

![fear](https://github.com/user-attachments/assets/714d435a-d718-488e-8f47-c054d6563877)

![rose](https://github.com/user-attachments/assets/c61f86b7-b552-40dc-8bcc-b989883b38d5)

![freeze-opt](https://github.com/user-attachments/assets/a5a6f071-d8a5-482c-bfca-3f9e48a3672a)

![blue dragon](https://github.com/user-attachments/assets/281f6b4c-4834-4e93-94f3-eeac606b8295)

![star](https://github.com/user-attachments/assets/8751d34c-0f20-4f59-b5c2-a06d5c3d047c)

**Comment by theflyingzamboni** [comment]
Fixed by commit 5cf2d9d
