### ISSUE TITLE
Wrong UV Data (Texture) over Meru and Lenus "Lenus Death" in-Battle CutScene

### ISSUE THREAD

**Issue by dragoonsouls** [Legend-of-Dragoon-Modding/Severed-Chains#1827]
As said in the title, Lenus and Meru have wrong UV Coordinates specially in their Face Texture, maybe present in other parts of their Models.
![Meru_wrong_UV_marked](https://github.com/user-attachments/assets/52791774-5151-4cd2-80ab-0651a24c4c82)
![Meru_wrong_UV_2_Marked](https://github.com/user-attachments/assets/8a254c23-7c41-4c5d-a4b5-e6a8e307607f)
![Lenus_Wrong_UV_2_Marked](https://github.com/user-attachments/assets/82571636-3038-439c-a2fa-912f643a94aa)
![Lenus_Wrong_UV_Marked](https://github.com/user-attachments/assets/ac5ae197-d4ec-43d8-99e2-914db27b300c)

**Comment by dragoonsouls** [comment]
Two additional Pictures of Meru UV Placement "in good shape" as example...
![Meru_FT](https://github.com/user-attachments/assets/a5ddadc6-e95c-47bf-8b24-56d57e1a501f)
![Meru_FT_2](https://github.com/user-attachments/assets/b3bbfa07-7c70-4ecd-8d77-a7a6dbdc5047)

**Comment by dragoonsouls** [comment]
Two additional picures of Lenus this is the model used too in that In-Battle CutScene, "in good shape".
![Lenus_TF](https://github.com/user-attachments/assets/b029f4d2-bab5-4098-9b10-b15331976d50)
![Lenus_TF_2](https://github.com/user-attachments/assets/4cd0b8ea-bfbc-455a-aa5b-9d8b2e0e6056)

**Comment by dragoonsouls** [comment]
After re-run the scene again, it show the Scene as intended with no graphic errors...
Lead Coder Monoxide said that possibly could be a Race Condition.

**Comment by warblgarbl** [comment]
Leather straps on her chest are wrong too. In battle model for reference:

![image](https://github.com/user-attachments/assets/fe6d796c-ecf2-4e71-be37-1520e93588f7)

**Comment by dragoonsouls** [comment]
surely part of the wrong UV location...

> Leather straps on Meru's chest are wrong too. In battle model for reference:
> 
> ![image](https://private-user-images.githubusercontent.com/136350269/390892105-fe6d796c-ecf2-4e71-be37-1520e93588f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4MzQwNTEsIm5iZiI6MTczMjgzMzc1MSwicGF0aCI6Ii8xMzYzNTAyNjkvMzkwODkyMTA1LWZlNmQ3OTZjLWVjZjItNGU3MS1iZTM3LTE1MjBlOTM1ODhmNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQyMjQyMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNzFmOGM4ZTcyZWYwYmZmY2M5NjcyYjQ0NTZhY2Q0YTQ3ZWZlYThjYmU1YzI5YjM3NmE0MzJjNWJmZGE5ZWM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.pKirsLDpFxcVWALoHL0H3q0ptSNLs_NzDXqLt0XF7qg)

**Comment by dragoonsouls** [comment]
https://youtu.be/ijsGgHFTGrs -> Full Video to check

**Comment by LordMonoxide** [comment]
I was able to trigger texture loading race conditions by adding a random delay to the file loading code
![image](https://github.com/user-attachments/assets/6be1dc1c-9f6b-4537-9057-4b74966d5c36)
