### ISSUE TITLE
Kamuy softlock

### ISSUE THREAD

**Issue by avionanx** [Legend-of-Dragoon-Modding/Severed-Chains#1836]
Tree doesnt die

**Comment by LordMonoxide** [comment]
From Icarus:
> either scriptstates are loaded in wrong order or gamevars [45][2] and [45][3] dont get loaded properly/get overridden somehow

**Comment by LordMonoxide** [comment]
Script states are allocated in order each frame, and it wraps around when it reaches the end. If one gets allocated in the very last available slot, the next one would get allocated in the first available slot, and I'm pretty sure that would make them tick in the opposite order than what was expected 
See the not very well named ScriptManager.upperBound

However, if this was the case, a lot of scripts would have to be allocated at that time

**Comment by avionanx** [comment]
from Drew
![image](https://github.com/user-attachments/assets/d642b6f9-2ff8-468f-87e2-961b13af1a0d)

**Comment by LordMonoxide** [comment]
This was reproduced by adding a random delay to the file loading code. It is 100% a file loading race condition.
