### ISSUE TITLE
Empty slots stuck on CharSwapScreen

### ISSUE THREAD

**Issue by warblgarbl** [Legend-of-Dragoon-Modding/Severed-Chains#1841]
With unlock party, empty active slots can't be selected to be filled in. Probably related to 12d3fa3?
~~It's also no longer removing gaps in the active slots on exit. (ex: solo slot 1 or 2 doesn't move to slot 0)~~
Must've been imagining that part.

**Comment by LordMonoxide** [comment]
Closed by #1844
