### ISSUE TITLE
Incorrect blending during Selebus' zambo hands

### ISSUE THREAD

**Issue by theflyingzamboni** [Legend-of-Dragoon-Modding/Severed-Chains#1848]
![image](https://github.com/user-attachments/assets/fb2a315a-d1e0-4581-b6df-4911706000c8)

**Comment by LordMonoxide** [comment]
This appears correct, but missing a lighter overlay. You can see the yellow underneath.

**Comment by theflyingzamboni** [comment]
Apparently SC is correct, epsxe and the videos recorded from it are wrong.
