### ISSUE TITLE
Scissoring Causes Voidvitz to Appear in Zackwell Cutscene

### ISSUE THREAD

**Issue by Zychronix** [Legend-of-Dragoon-Modding/Severed-Chains#1885]
https://cdn.discordapp.com/attachments/1171862923870752829/1320207448388276294/Clip_-_12212024_75240_PM.mp4?ex=676a13ff&is=6768c27f&hm=757906d92cea8cfc331f77932be37f768eaea8d69eca028f858fc0df5973743a&

Commit [f82c66c92b03c4952a0a757d6a3b4e62a5edabc3](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/commit/f82c66c92b03c4952a0a757d6a3b4e62a5edabc3)
Causes Voidvitz to appear in the cutscene with Zackwell.

**Comment by LordMonoxide** [comment]
Don't know how or why this is happening. The scissoring for the text is somehow being applied to the framebuffer render even though scissoring is disabled. Resetting the scissor rect to the whole screen fixes it.
![image](https://github.com/user-attachments/assets/cb1b42e8-23c8-4f76-88da-9fee6888bec9)
