### ISSUE TITLE
Level Up animation persists across battle screens

### ISSUE THREAD

**Issue by zack37** [Legend-of-Dragoon-Modding/Severed-Chains#416]
Whenever a character levels up, the text animation plays. If the animation is canceled early (by exiting the post battle screen as early as possible before the animation is finished playing), on the next post battle screen, the Level Up animation continues playing from where it left off.

I'll see if I can get a video of it at some point

**Comment by LordMonoxide** [comment]
Fixed in 16d269f4300aa2fed975aec4eec4433891998197
