### ISSUE TITLE
Effect bugs

### ISSUE THREAD

**Issue by theflyingzamboni** [Legend-of-Dragoon-Modding/Severed-Chains#428]
We should really have a list of remaining effects bugs, and I'm not sure it makes sense to have separate issues for each one we come across, despite how satisfying it is to close a bunch of issues. I'll add to the list as other people mention things.

New:
- ~~Guard heal effect is tilted slightly?~~ (fixed at some point during remathening)
- ~~Dart far too bright on saves/warp pads~~ (fixed by #700)
- Warp effect too bright/flashy
- scriptSetLightDirection, scriptGetLightDirection, ~~BttlLightStruct84Sub38 - .12~~ -> psxdeg?
- Rain in Melbu 3rd gen cutscene is whack
- Melbu flattened me on the night stage (set Y scale to 0)
- Belzac's Grand Stream has a messed up texture, either fp color error or clut error

SC:
- **_#58_**
- ~~#289~~ (fixed by #440)
- ~~#308~~ (fixed by #440)
- #300 (full fixedness state unknown)
  - ~~Some rain lines go sideways in places like the Third Gen cutscene and Rainbow Breath~~ (fixed by #501)
  - ~~Ferry of Styx lines during charge-up only radiating in one direction instead of all around~~ (fixed by #488)
  - ~~Heal particles don't swirl right~~ (fixed by #511)
  - ~~Line particles during Kanzas' Kamehameha charge-up wrong~~ (fixed by #660)
  - ~~Line particles during explosion in Kanzas' daddy bounce around instead of radiating~~ (fixed by #660)
  - ~~Lines during Lloyd's instakill and dome attack go nuts~~ (fixed by #660)
- ~~#353~~ (fixed by #1085)
- ~~#355~~ (fixed by #440)
- ~~#356~~ (closing PR currently unknown) 
- ~~Weird translucent rectangle visible during First Gen and Fifth Gen cutscenes (seems to be related to lens flares)~~ (fixed by #654)
- ~~#367 (this is very likely the same bug that affects so many of the lightning effects)~~ (fixed by #433)
- ~~#406~~ (fixed by #459)
- ~~#414~~ (fixed by #456)
- ~~Reversed Dancing Lights gradient~~ (fixed by #441)
- ~~Effects like mouse bite and Burn Out keep growing~~ (fixed by #420)
- ~~Death Dimension, Melbu's screenshot attack, and Kubila's frog not rendering the screenshot~~ (fixed by #433)
- ~~Some transparent effects don't blend/display properly (like red glow in Death Dimension) or are invisible (Trans Light explosions)~~ (fixed by #433)
- ~~Some sprite effects not lit correctly (like overlays on red glow in Death Dimension)~~ (fixed by #433)
- ~~TINY HANDS 👐~~ (fixed by #435)
- ~~Lavitz's damaged chest plate lit wrong~~ (fixed by #436)
- ~~Incorrect rotation in some effects (Psyche Bomb haze, end of Spectral Flash)~~ (fixed by #441)
- ~~Background textures during Melbu's planet attack are scrambled~~ (fixed by #481)
- ~~Some normals during oof (like Albert's hands when receiving DS) messed up~~ (fixed by #440)
- ~~Some chests rendering incorrectly~~ (fixed by #440)
- ~~Items not following parabolic arc~~ (fixed by #441)
- ~~Normals seem to be wrong on Albert's cape in combat; should be smoothly lit~~ (fixed by #514)
- ~~Weapon trails are messed up~~ (fixed by #597)
  - ~~Kanzas' daddy crashes game when attacking character in slot 0~~
- ~~MCQ backgrounds in combat are transparent~~ (fixed by #502)
- ~~Virage laser attack particles missing~~ (fixed by #459)
- ~~??? other particles~~ (fixed by #459?)
- ~~Fletz planetarium effect messed up~~ (fixed by ???)
- ~~"The End" text should have shimmering overlay~~ (fixed in 6a77190)
- ~~Spear Frost ice has turned bloody~~ (fixed by #567)
- ~~Item mashing percent text overly bright~~ (fixed by #575)
- ~~SP text makes "holes" in counter shield~~ (fixed by #575)
- ~~Healing potion and some other rings too large~~ (fixed by #578)
  - ~~Arrow shooter detonating arrow (color disc flash too big)~~ (fixed by #578)
- ~~Dust cloud around injured Virage after claw attack clustered behind party instead of spread around Virage~~ (fixed by #579)
- ~~VDF effects with multiple instances don't render properly~~ (fixed by #584)
  - ~~Only one light beam during Grand Jewel heal~~
  - ~~Selebus' grabby straps are invisible~~
  - **_Selebus' zambo hands aren't moving (working, but placement of hands is still incorrect)_**
- **_Enemy spawners that you have to destroy in that one room with the maze should turn blue after destroyed (see screenshot in comment below)_**
- ~~Dragoon Doel's sky lightning ball attack thing has some crazy flashes~~ (fixed by #566)
- ~~Gravity Grabber circumscription messed up~~ (fixed by #656)
- ~~Star Children meteors and impacts not rendering properly~~ (fixed by #646)
- **_Weird dark hexagons when using moves in dragoon space against Lloyd_**
- ~~"Can't Combat" textbox background black~~ (fixed in 60a69630)
- ~~Shana Transformation~~
  - ~~Feather movement wrong~~ (fixed by #655)
  - ~~Camera not zooming during first part~~ (fixed by #652)
- ~~Lens flares too bright~~ (fixed in d9a741ce)
- **_Lloyd's dome growing animation is messed up_**
- **_Blue Sea Dragon ice textures wrong_**
- **_Weird lines in Lenus' whirlpool_**
- ~~Pew pew boat lasers~~ (fixed somehow by c71afb31)
- ~~Wmap clouds don't seem to be rendering?~~ (fixed by #850)
- ~~Wmap smoke animation seems wrong~~ (fixed by #841)
- ~~Location text box on Coolon world map screen sometimes doesn't render, sometimes does~~ (yet to see this occur in opengl)
- **_Wingly city Wmap teleportation effect got borked_**

Retail:
- ~~Dart's missing left hand during part of oof~~ (fixed by #439)
- ~~Lavitz's damaged chest plate visible on ground behind Albert's head~~ (fixed by #439)
- A piece of the floor behind Lloyd immediately after oofing Lavitz is getting erroneously culled (may not be fixable until opengl)
- #473 
- Some character portrait color channels get misaligned in the menu

**Comment by LordMonoxide** [comment]
![Image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/437657/24eb1ae3-42c8-47f2-a40e-dc7a7b91db2c)

**Comment by DrewUniverse** [comment]
Issue regarding Selebus - Zombie hands aren't animating as they should.
![Uploading bug-selebus-zombiehands.gif…]()
![bug-selebus-zombiehands-proper](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/70291675/8c122804-a595-4107-bd0d-1b090e959d86)

Issue regarding Selebus - physical attack bandage wraps are invisible/not rendering.
![bug-Selebus-phys-attack](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/70291675/883f6062-d04e-4984-b997-fcd8c3ecb168)
![bug-selebus-phys-attack-proper-opt](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/70291675/83fa83b4-c472-46f9-854f-fe02866d41bb)

**Comment by theflyingzamboni** [comment]
Daddy issues:

![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/55669985/8df72304-49b2-4bd9-864f-9e240342e594)
![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/55669985/3c2ec75b-ffec-4a95-b916-14a8e4b201e5)
![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/55669985/36ff6a8c-2d19-4e32-b518-68bf9655ea20)
![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/55669985/8ec9e9cd-f0c7-4c85-a757-4c76f9258992)

**Comment by Ink230** [comment]
Started noticing issues with red dragoon attack red lines and Flower Storm lines on Albert. These new, intended or known?

**Comment by Zychronix** [comment]
The ring effect from Healing Potion and other items like it are changed to the effect that Guard uses.

**Comment by Zychronix** [comment]
![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/14896608/e9612733-e5c0-48aa-8851-f5a2fef18dfb)
The lightning effect for spark net should be attached to the spark net ball itself.

**Comment by Zychronix** [comment]
Urobolus gas breath attack goes to the side instead of heading towards the players.

**Comment by Zychronix** [comment]
The trail behind monsters going diagonal is slightly off.
![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/14896608/ad5b6bca-c36c-47ed-9321-36ea0a2d30be)
![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/14896608/a9ce2562-eb32-430c-8087-249818fe59f3)

**Comment by Zychronix** [comment]
Elemental weakness indicator is missing

**Comment by Zychronix** [comment]
Dart trips over the carpet in princess room.

**Comment by Zychronix** [comment]
Healing Rain only shows two rays instead of three unless the third is inside one of the other two rays.
Down Burst's petals are rolled up into a ball.
Pellet's bullets are sideways. 
Fatal Blizzard is flipped.
Damage Numbers are very far from intended target.

**Comment by theflyingzamboni** [comment]
Grand Stream bug listed above
![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/55669985/93ac69f8-00c8-45db-bd3d-43106f4240fb)

**Comment by zonryu2** [comment]
rat bite attack effect is massive 
![ezgif-2-c9a92ed335](https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/assets/156882688/2c8a4f49-ef2f-45ee-8429-e0d292ee814e)

**Comment by Meruheart** [comment]
In the first scene of Hellena with Frueguel and Lloyd, when Llody aims Frueguel with the sword, he doesn´t look at him

**Comment by Meruheart** [comment]
This happens if you select "Carried" option when talking with a Merchant (it happened in Seles forest)

![image](https://github.com/user-attachments/assets/7ac01686-ae8d-4851-b57c-9b4bf4f0370c)

**Comment by Meruheart** [comment]
In items tutorial with the Forest´s Merchant there is this visual bug, it happens with all the text inside "Attack items element" (second option), it´s very close to the bottom of text box
![image](https://github.com/user-attachments/assets/ba8f42be-d8b2-40c0-8df7-cb89842c89b3)

**Comment by theflyingzamboni** [comment]
All still-extant errors shifted into own tickets.
