### ISSUE TITLE
Crash mashing buttons rapidly - Dragoon Addition [Auto]

### ISSUE THREAD

**Issue by dragoonsouls** [Legend-of-Dragoon-Modding/Severed-Chains#431]
When mashing buttons during Dragoon Addition will leads into a crash...
[Daddy_Crash_multi.txt](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/files/11290501/Daddy_Crash_multi.txt)

**Comment by theflyingzamboni** [comment]
This appears to be related to the hack we use for auto-daddies. Using whatever flag triggers auto-daddies in Special would circumvent this.

**Comment by LordMonoxide** [comment]
This is no longer an issue
