### ISSUE TITLE
Fruegal 1 targeting anomaly

### ISSUE THREAD

**Issue by Chocolate06** [Legend-of-Dragoon-Modding/Severed-Chains#461]
If you select attack/magic items, and then move from the left warden to the right warden (or start on the right warden), you can no longer go back to the left warden by pressing left. It tries to select Fruegal which the game corrects and makes you go back to the right warden. You can get back to the left warden by pressing right. Also if you kill the right warden first, pressing left on the left warden tries to select Fruegal. No issue going left from the left warden if both are alive.

Does not crash or cause any other issues as far as I can tell. You can simply continue by killing both wardens and then Fruegal is targetable along with the senior wardens.

This does not happen in retail, using either left or right cycles between the two wardens and Fruegal is not targetable until both are dead.

**Comment by Ink230** [comment]
![image](https://user-images.githubusercontent.com/29797557/236646043-8a03936e-fecc-48fc-828c-94c78ea84ae9.png)

**Comment by LordMonoxide** [comment]
This is no longer an issue
