### ISSUE TITLE
"Goods" screen acting as two separate lists

### ISSUE THREAD

**Issue by Chocolate06** [Legend-of-Dragoon-Modding/Severed-Chains#505]
For example, if you go right from the first row on the left side, you end up on the first row on the right. Then if you go down to the fourth row on the right side, pressing left takes you back to first row on the left. Pressing right from here would then take you back down to the fourth row on the right. I assume it's following the same logic from the "Inventory" screen where we do have two separate lists.

In retail when pressing left or right in "Goods", you stay on the same row.

**Comment by Ink230** [comment]
I believe this was made as an intentional change. A lot of the UI is already fairly deviated from retail behaviour to either be more convenient or more practical.

Is there an issue this causes for playability?

**Comment by Chocolate06** [comment]
No issue for playability, was simply pointing out something different from retail.
