### ISSUE TITLE
Music/sound issues

### ISSUE THREAD

**Issue by LordMonoxide** [Legend-of-Dragoon-Modding/Severed-Chains#570]
- ~~Inventory music has extra percussion that shouldn't be there~~
- ~~Crash in battle engine cutscenes~~
- ~~No music/sounds in battle engine cutscenes (scriptLoadBattleCutsceneSounds)~~
- ~~Popping sounds during opening song~~
- ~~A lot of hit effects are distorted in weird ways~~
- Combat music start is a bit delayed
- Addition names still cut out
- ~~Sound thread crashes after combat when victory music should play, recovers when entering SMAP (might be particular to wingly zone battle music)~~
- Combat music has assorted issues still (like some notes not sustaining)
- ~~Music doesn't stop before FMVs start (start new campaign to test)~~

**Comment by theflyingzamboni** [comment]
Popping sounds during opening song.

**Comment by LordMonoxide** [comment]
I think we can finally close this out now that we have the new music engine
