### ISSUE TITLE
Switching audio devices results in a freeze

### ISSUE THREAD

**Issue by avionanx** [Legend-of-Dragoon-Modding/Severed-Chains#592]
[SPU legend.core.spu.Spu:142] WARN : SPU running behind, skipping ticks to catch up

Turning off bluetooth headphones results in a freeze with the warning above.

**Comment by avionanx** [comment]
Switching from speakers to headphones did give the warning, but there was no freeze.

**Comment by Ink230** [comment]
• Occurs on Windows 10 by disabling an audio device or switching audio devices
• Occurs more frequently on non-Debug modes
• Campaign Screen never crashes on Debug mode swapping devices but does crash 80% of the time on non-Debug modes
• Submap crashes on debug or release mode once trying to open (potentially load new sounds) the menu
  • Silently failing I suppose

![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/29797557/576496ef-bc4d-42b4-b45e-14f8598cbb30)

• Can't seem to find an exception being produced, I think with it being a Windows issue, getting an exception may not be possible
  • Doesn't produce one with local try catch blocks or using global breakpoint settings
  • Just goes non-responsive

• Is producing an event log on Windows
![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/29797557/b62593c0-4cfa-46d1-8d67-01f01ac5b7d6)

![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/29797557/34846cd4-146c-44c5-9522-80dcdd794a73)

  • No further info available

**Comment by LordMonoxide** [comment]
Note: seems to work in Windows 11 and Mac (Intel, unsure about M1)

**Comment by Ink230** [comment]
• Disabled tick skipper
• Changed all SPU try catches to catch generic Exceptions
• Still went unresponsive with no exception thrown

**Comment by LordMonoxide** [comment]
Closing since we use a different audio API now
