### ISSUE TITLE
Resolution Config in Options

### ISSUE THREAD

**Issue by Sonlen1414** [Legend-of-Dragoon-Modding/Severed-Chains#631]
Basically issue name, I think it would be beneficial to be able to set the resolution settings inside the options menu in game, rather then just the config file. Potentially bonus idea for it to allow forced aspect ratio lock so you don't input a ratio that would potentially stretch, assuming the game itself doesn't already handle that properly.

**Comment by theflyingzamboni** [comment]
This will be a non-issue in RB3 with OpenGL, since it will just have normal resolution options.
