### ISSUE TITLE
Screw Shell overshoots target

### ISSUE THREAD

**Issue by theflyingzamboni** [Legend-of-Dragoon-Modding/Severed-Chains#707]
When attacking, Screw Shell zips through the target:

https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/55669985/7827cd14-6ad0-49fc-913f-c71d4b4ca9a4

**Comment by dragoonsouls** [comment]
Screw Shell became a piercing arrow

**Comment by avionanx** [comment]
calculateEffectTransforms is off the mark

**Comment by LordMonoxide** [comment]
Still happening even after recent fixes to that method
