### ISSUE TITLE
Minor Fire Bird visual issues

### ISSUE THREAD

**Issue by Zychronix** [Legend-of-Dragoon-Modding/Severed-Chains#729]
Camera bug 

https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/14896608/022676c2-0799-46f9-9170-0af07480aa34

Animation lagging issue

https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/14896608/3d85ecb3-5c02-4e3b-80c7-65623fc2611e

I don't know what to call this one

https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/14896608/27cf9304-b4a8-46a7-a475-20c185933659

**Comment by LordMonoxide** [comment]
Closing as this is pre-opengl
