### ISSUE TITLE
[OpenGL] Textbox clipped offscreen

### ISSUE THREAD

**Issue by DrewUniverse** [Legend-of-Dragoon-Modding/Severed-Chains#783]
I believe this is just due to the current method of zooming in on submaps. It looks like it's a 16:9 crop of the original 4:3 zoom level, which is great to avoid black bars, and simultaneously results in visibility issues like this. 

![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/70291675/a8acb280-5459-4c1a-968f-651ec151169b)

**Comment by LordMonoxide** [comment]
Resolved at some point
