### ISSUE TITLE
[OpenGL] In combat, party member facing sideways after being launched by Melbu's 2nd form.

### ISSUE THREAD

**Issue by DrewUniverse** [Legend-of-Dragoon-Modding/Severed-Chains#796]
Note: party member faces forward again once they take a new action.
![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/70291675/7606371b-45e9-4e6b-b4a7-adb6458dc9b7)

**Comment by theflyingzamboni** [comment]
Fixed by `https://github.com/Legend-of-Dragoon-Modding/Severed-Chains/commit/f6d6c3ef4d16f8cc7989a843a4dc6c2c735c78da` maybe?
