### ISSUE TITLE
[OpenGL] Background geometry does not load during Generation cutscenes for Melbu.

### ISSUE THREAD

**Issue by DrewUniverse** [Legend-of-Dragoon-Modding/Severed-Chains#797]
![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/70291675/fdc686df-c144-431b-9904-79e563965b71)

**Comment by LordMonoxide** [comment]
Resolved by 9bd976aa6763533b22c4fbaf769eac656efbe185
