### ISSUE TITLE
World map Dart arrow animation resets too early, making it choppy

### ISSUE THREAD

**Issue by LordMonoxide** [Legend-of-Dragoon-Modding/Severed-Chains#874]
This arrow, zoom out once to view
![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/437657/c671c67f-123e-46f4-979d-37b4965ffcd6)

**Comment by theflyingzamboni** [comment]
All sprites in the series are used for the correct duration, the sequence is just crap and has a big jump between the vertical and the sprites on either side of it in the sequence.
