### ISSUE TITLE
Is Urobolus in the wrong spot?

### ISSUE THREAD

**Issue by LordMonoxide** [Legend-of-Dragoon-Modding/Severed-Chains#881]
![image](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/437657/5a9057f0-affe-4679-b01b-e2c637ef872f)

**Comment by theflyingzamboni** [comment]
Yes.

**Comment by KiameV** [comment]
There appears to be a scaling issue in the rendering.
From the file, Vector3 is -9216, 0, 128

I went back to `main` and verified that the values loaded from the file are the same.

From the debugger, I started to play around with the x/z position of the Urobolus and found that _new_ x/z are roughly -8000, 0, -800 to have the snake in the correct position.

**Comment by KiameV** [comment]
Broken between HEAD~250 `9dd2022d489f64e7145d8b5599cf0e8fe2b1799a` and HEAD~200 `2c8f0c6895c3dc53fb140943f40556522a276b70`

Having trouble compiling builds between these two branches

**Comment by KiameV** [comment]
I see in commit https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/commit/227325998fc145b4014da54befa7cc6a519ca20c that the meshes changed from `Obj`s and to `Tmd`s. Does this change the coordinates / offsets?

**Comment by KiameV** [comment]
After reviewing the diffs, nothing popped out.

Looking back at the difference between previous version and current, SBtld.java has `data.model_148.coord2_14.coord.transfer.set(s5.pos_02);`

The matrix in both cases are identity and the pos_02 values are the same. I'll need to know where the rendering happens.

**Comment by KiameV** [comment]
I took to comparing video from July release to current main.opengl
`Left release --- Right main.opengl`
![orig](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/26260306/dfc1823c-03c0-4cf2-b019-e6e7c8a98dd7)

I noticed the shadow in the current release is an issue. The snake also appears to be in the same position. In the next screen I compare the snake's scale (head) and position (left/bottom squares).

I believe this is an issue with clipping. The cave's vertex is somehow interfering with rendering the snake's shadow and is clipping in way the original game did not.

![marked](https://github.com/Legend-of-Dragoon-Modding/Legend-of-Dragoon-Java/assets/26260306/4eca4a8a-1e1c-495d-b651-486d2f6adbf6)

**Comment by LordMonoxide** [comment]
I'm thinking this might actually be due to LOD's janky Z depth code... I haven't verified this theory but it looks like the positions the same, but the new SC code is actually rendering it "correctly", i.e. the model _should_ be intersecting the stage, but the old code renders the model in front of the stage. Maybe we'll jack freecam into 2.1 and see what's going on
